### ISSUE TITLE
Create note from placeholder Wikilink

### ISSUE THREAD

**Issue by bjackman** [foambubble/foam#1141]
### Is your feature request related to a problem? Please describe.

Sometimes I create a Wikilink for a note I intend to write. Then when I run the "Create New Note" command I have to re-type the name of the note.

### Describe the solution you'd like

I think a lot of things would work here. I guess the simplest might be that the "Create New Note" command defaults the name to the placeholder under the cursor, if one exists?

### Describe alternatives you've considered

- Could have a separate command for "Create New Note for Current Placholder"
- Could also have this as an option in the graph view (not mutually exclusive with other suggestions)

**Comment by riccardoferretti** [comment]
Defaulting the new note command to the placeholder under the cursor is an interesting idea, I do wonder though whether it could lead to "unexpected" result for people not familiar with the feature ("why does it ask for the title some times while others it doesn't?").

Also because currently you just need to cmd+click on the placeholder to create a note using the placeholder as title.

So, not sure: I am not opposed in principle, I am not enthusiastic either.
Let's see what others have to say about the feature.

**Comment by bjackman** [comment]
> "unexpected" result for people not familiar with the feature ("why does
it ask for the title some times while others it doesn't?").

I was envisaging that the dialog pops up regardless, i.e. the user
"journey" is the same, just that it would be pre-populated.

> Also because currently you just need to cmd+click on the placeholder to
create a note using the placeholder as title.

Huh, _that_ is interesting though! I will check next time I use it... This
is actually probably the behaviour I would expect, maybe it is not working
for me for some reason. Will get back to you!

**Comment by bjackman** [comment]
Huh, right - Ctrl+click does indeed work. That certainly solves the issue for me. I realised I was subconsciously using my go-to-definition shortcut instead of the ctrl-click. Any idea why one works and not the other?

**Comment by riccardoferretti** [comment]
Yeah placeholders are treated as links that don't have a definition.
ctrl+link is following the link, which creates the note from the placeholder

**Comment by riccardoferretti** [comment]
I am going to close this, let me know if there is anything else to note here
