### ISSUE TITLE
Clicking on placeholder from list would bring to location in note

### ISSUE THREAD

**Issue by wrgrant** [foambubble/foam#1145]
### Is your feature request related to a problem? Please describe.

Currently when you click on a placeholder entry in the sidebar, it creates a new note in the root of the vault.

To me this is a strange UX.

I would rather be dumped into the note where the placeholder is called out so I can get a context for why that placeholder exists and if there is any extra context or links that make sense to add there.

With the current behavior, I'm faced with a blank file that I don't know what to do with. That provides no context.

If I want to get to the placeholder, I need to do a VSCode content search to find where the placeholder was defined.
This is rather clunky.

### Describe the solution you'd like

Expected behavior would be to click on a placeholder entry in the sidebar and land at the point in the existing note where the placeholder was defined. Using the exact same behavior as when you click on a tag for a file from the Tags Explorer pane.

### Describe alternatives you've considered

Searching via VSCode content search.

**Comment by badsketch** [comment]
![Screenshot 2023-01-17 231244](https://user-images.githubusercontent.com/8953212/213082728-0d48c6ec-1243-4a29-acf4-a5392e650abe.png)
I like how in certain file lists in vscode such as the source control tab, the context actions include jumping to the source, so what you're saying makes sense to me.

One thing we'd need to think about is placeholders that are referenced in multiple places. Currently, two separate files with the same placeholder name produces one placeholder, so I'm wondering the best way to display all sources.

**Comment by riccardoferretti** [comment]
Currently:
- the placeholder panel doesn't show where placeholders are coming from (whereas the tags panel does it for each tag)
- clicking on the placeholder item triggers the flow of placeholder creation (which currently creates the note in the root)

We are about to release a setting to create a new note either at the root or in the current folder, this will affect the flow for placeholders.

Idea:
- I agree it would be helpful to expand on a placeholder to see all the places where it's referenced (like the tags panel)
- clicking on one of those notes would navigate to the note (same behavior as in the tags panel)
- this means that clicking on it will no longer create the placeholder
  - which is not necessarily a problem, so the above could simply be a solution. If you want to create the note, you can then do it from the wikilink in the editor

Otherwise to still enable the creation of the placeholder note from the panel, we have a few options:
1. do something similar to what we did in the tags explorer, where the first item of the children is "Create note for placeholder". Clicking on this would follow the standard flow of creation, as if triggered by cmd+clicking on the link in the first child note for the placeholder
2. add a `+` context action to the placeholder, to achieve the same as above
  -  I would want the pattern to be the same between tags and placeholders, so in the second case I would migrate the tags explorer to the same pattern  
3. add a `+` context action to each child note, to trigger the creation process as if it were done from that note
  - feels over-engineered

Thoughts?

**Comment by wrgrant** [comment]
From a high level UX perspective, the value of things like tag and placeholder lists is in seeing where they are defined, and quickly being able to jump to the context where they are defined. This is what search functionality in VSCode is so great at. And tag and placeholders are just sort of a specialized search functionality.

In my opinion / workflow, there is almost zero value in being able to create a note from a placeholder when it is just a big list of placeholders next to each other. Because each placeholder will have a different relative or logical value compared to the context it is defined in.

For example: a placeholder may be a person's name. I have a folder where all people are defined that a 'name' placeholder should be created in called `People`. 
In another case, a placeholder may be a date, which should go in my `/Journal` directory.

I would need many different 'cases' for where a placeholder should be created, to the point where it is much easier to just go manually create that file in the file explorer and link to it. I guess having the file created for me and dropped in `root` would save a few clicks.

But in any case, the auto-create functionality is a much lesser use case for me.
Much more useful and important is being able to quickly get to the definition place of a tag or placeholder, so I can then use my brain to make the decision about where (and if) to create the actual file to be referenced. Because I'm primarily using the tags and placeholders functionality to navigate through my notes, separate from actually creating them.

So I would argue that the best course is indeed to re-work the Placeholder tab to function similar to the Tags Explorer.

* You get a breakdown of what files referenced a placeholder (like Tags Explorer currently)
* The default action of clicking a reference is to take you there (just like @badsketch mentioned above)
* (optionally) there could be an additional button to the right of each entry with the "new file" button that could trigger creating an empty version of the file

PS: what would really supercharge the placeholder creation functionality would be to open a query window, similar to `Create from template` where you could do a search lookup of all directories in your vault, type a few characters of a folder name, then Foam would drop the file there :)

**Comment by riccardoferretti** [comment]
From #1144 - I found interesting the other use case which is about placeholders management and creation from the panel. I would like to find a solution that works for both use cases. Integrating the "Create from template..." for the placeholder via the panel might actually be an interesting approach.

Thoughts?

**Comment by riccardoferretti** [comment]
I have implemented some of the feedback from this task in #1196 - which will be released later today (0.22.0). 
Feel free to leave comments
