### ISSUE TITLE
Tag completition doesn't work anymore after update

### ISSUE THREAD

**Issue by mimmori** [foambubble/foam#1189]
### Describe the bug

After the [v0.21.2](https://github.com/foambubble/foam/releases/tag/v0.21.2) when i start to add a tag to a note (#something) the extension doesn't show the auto completition hint as it did before.
I also try to install the [v0.21.3](https://github.com/foambubble/foam/releases/tag/v0.21.3) version but there is no change in that behavior.

### Steps to Reproduce the Bug or Issue

Create a new file with markdown syntax. Start adding a title and after try to add a tag that is present in the tag explorer.

Example of file content:

```
# Title

#<your-tag-here>
```
### Expected behavior

I expect that a tag selection windows is shown to aid the tag insertion. (previous operating mode)

### Operating System Version

OS Name	Microsoft Windows 10 Pro (Version 10.0.19045 Build 19045)

### Visual Studio Code Version

1.77.3

**Comment by riccardoferretti** [comment]
Let me look into it, probably related to #1183 - cc @jimgraham

**Comment by jimgraham** [comment]
Tried the example on the default foam-workspace on Windows 10, VS Code 1.77.3

I got what I expect (see video)

## `v0.23.1`

https://user-images.githubusercontent.com/430293/231885147-55e75af1-e932-4ddf-af1b-437d3173d616.mp4


## `v0.21.0`

One distinction between `0.23.1` and the older version is that you need to type at least one character of the tag. This is because the tag completion is using a more restrictive regex (`HASH_REGEX` instead of `#(.*)`


https://user-images.githubusercontent.com/430293/231886510-3ba890d5-4d07-43f8-8045-ebe4abd6717b.mp4

**Comment by riccardoferretti** [comment]
Thanks for the clarification @jimgraham
I must have missed the change in behavior, as for me #1182 was about avoiding `#` to cause the tag to be triggered after the space.

I still think it's useful to have `#` trigger the full list of tags, we should support that

**Comment by jimgraham** [comment]
Happy to change it and I can fix it this weekend. It will require a different regex than the exported `HASHTAG_REGEX` as that is what is requiring the additional character
