### ISSUE TITLE
Tasks support

### ISSUE THREAD

**Issue by alper** [foambubble/foam#1198]
### Is your feature request related to a problem? Please describe.

I'd like to be able to track tasks across notes.

### Describe the solution you'd like

A filterable sortable list of tasks pulled from the entire workspace.

Would something like this be doable?

### Describe alternatives you've considered

None

**Comment by riccardoferretti** [comment]
At the moment task management is not within Foam's scope.
The rule of thumb I use is whether the network aspect of the knowledge base is essential/useful to the task - otherwise I think it is better to leave that part to other extensions that are specialized in that (and that in my experience never conflict with Foam itself)

**Comment by alper** [comment]
Is there an extension for tasks that's known to work well with Foam?
