### ISSUE TITLE
Multiple/batch file renaming doesn't update links

### ISSUE THREAD

**Issue by bserrao** [foambubble/foam#1222]
### Describe the bug

I'm using dots in filenames to define some type of hierarchy (similar to folders)... For instance p.rebranding.documentation.md, p.rebranding.scratch.ddmmyy.md, ..., for a project related to rebranding. When this project comes to an end i rename all the files.. imagine... from p.rebranding... to a.rebranding... (archives).
In order to do this batch renaming i'm using batch rename extension in vscode which was the most straightforward extension i found for this purpose, and this way the links, referrals aren't updated to reflect the new filename. The trigger that detects the filename rename only works when i use the native single file rename of vscode.
How does foam become aware of filename change? Is there a way i can trigger that when renaming multiple files?

Thanks, 

### Steps to Reproduce the Bug or Issue

1. Create some files with links
2. Use the batch rename extension (or other batch filename renaming)
3. Check that the links weren't updated and refer to the old filename.

### Expected behavior

I would expect that foam detects the filename renames and trigger an update for all references.

### Operating System Version

Windows

### Visual Studio Code Version

1.77.3

**Comment by riccardoferretti** [comment]
We hook into VS Code `vscode.workspace.onWillRenameFiles` to monitor for file name changes, probably the way these extensions rename files doesn't trigger the VS Code event.

Quickly glancing at this extension: https://marketplace.visualstudio.com/items?itemName=JannisX11.batch-rename-extension

They use the FS module instead of VS Code `vscode.workspace.fs`, which might explain why VS Code doesn't trigger the event.

I recommend you suggest to the extension author to use the VS Code API, I can't guarantee it will fix the problem, but it might.
