### ISSUE TITLE
Add Recipe for creating a Foam workspace with GistPad

### ISSUE THREAD

**Issue by jsjoeio** [foambubble/foam#135]
Now that [GistPad](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.gistfs) supports interoperability with Foam, we should document it as a [Recipe](https://foambubble.github.io/foam/recipes).

**Comment by juanfrank77** [comment]
I think it's worthwhile saying that since Gistpad has support for .drawio files, there's a way folks can add diagrams to their Foam documents. 

What's left is to see how those diagrams would look like once the workspace is published. But I feel there's a lot of potential with that Gistpad integration, even allowing people to not go through the clone/commit/push process 😏

**Comment by jevakallio** [comment]
Fixed by #138
