### ISSUE TITLE
Proposal: Export to Anki

### ISSUE THREAD

**Issue by jasonwilliams** [foambubble/foam#140]
So we were having a chat on the discord server about how this could work.
I came across https://github.com/caisj-dev/SendToAnki which is a sublime plugin for sending markdown notes to Anki.

I believe we can add something similar to foam as a feature. The Anki api (via openconnect) is a HTTP REST interface, so should be easy to communicate with.

Ideally I imagine at the bottom of each markdown file you can add some quick Anki notes.

Some open questions:
- is it automatic? Or do you highlight a format then send (like the sublime version)
- what is the format of text we use for this? Ideally something that’s hidden from the preview version?
  - how does the [//begin] work? Maybe we could utilise that?
- it would be nice not to duplicate the Anki questions (if they already exist on Anki don’t add again)
  - this may be possible with the OpenConnect API

**Comment by jsjoeio** [comment]
I don't have an open issue for this but I think this also relates to another discussion we had on Discord around creating Anki cards and studying them within VS Code similar to this [flashcards extension](https://marketplace.visualstudio.com/items?itemName=kim-sardine.flashcards). 

I imagine some of the work overlaps with this feature.

**Comment by jsjoeio** [comment]
What are your thoughts on adding syntax to create spaced-repetition cards similar to how [RemNote](https://www.remnote.io/homepage)does it?

**Comment by jsjoeio** [comment]
![image](https://user-images.githubusercontent.com/3806031/87887875-cba89580-c9dd-11ea-8dcd-c44b509473e9.png)

For those who aren't familiar, here is a reference.

**Comment by jasonwilliams** [comment]
Reusing Remnote syntax could be a good idea. I’m not sure how we do that inside of a markdown file though? Does remnote have syntax highlighting? Could it be done in a code block and hidden from preview?

**Comment by jsjoeio** [comment]
Yeah, I haven't thought through that yet either. Oh, that's a good idea. Maybe that's possible

**Comment by jasonwilliams** [comment]
I'm leaning towards [`yaml`](https://yaml.org/) for syntax, there's already support for it in VSCode, we will have syntax highlighting and we should already be able to parse it.

**Comment by jasonwilliams** [comment]
I think flashcards could live as part of the markdown metadata (which i don't think foam uses yet), this also means it won't be rendered in the preview version.

https://github.com/ninjabachelor/markdown-yaml-metadata-parser

**Comment by jevakallio** [comment]
@jasonwilliams thanks for this suggestion! 

> I think flashcards could live as part of the markdown metadata

We call this type of yaml metadata "frontmatter" (as that's what it's typically called in static site publishing circles), and we'll be adding full support shortly. This means extension builders can use it for whatever metadata they need -- so big 👍 for that approach.

The one thing I don't know (as someone who doesn't do spaced repetition) is whether that's a user friendly approach? 

- Would you manually write the questions and answers for their flash card?
- Would you want to have them at the top of the file like this, or interspersed inside a markdown note closer to where the information is written?

Generally speaking, 
- I want Foam to enable people to use best-of-breed tools and methodologies that works for them
- Prioritise good and intuitive user experience 
- Allow new users to adopt habits and practices that are helpful for them. 

An ideal solution for Foam might look like:
- Initial lightweight implementation that's able to push content to existing tools
- Once the need for the use case is validated, consider [building/assembling](https://foambubble.github.io/foam/build-vs-assemble) something in Foam
- Using the same data format for both, so people can pick and choose, or gradually migrate, between approaches.

I'm not an experienced spaced repetition user, but I'd love to learn more, so perhaps I can add value as the novice user who vets the intuitiveness of the approach.

@jasonwilliams @jsjoeio if we can put together a proposal for this, I'd be happy to include it on the roadmap and discuss how to best add this support to Foam, whether as a built in feature or as a third party extension!

**Comment by jasonwilliams** [comment]
> Would you manually write the questions and answers for their flash card?

Personally yes, I don't think this is much of an issue, if you try to be too clever it ends up being complicated both for the user and the implementor. I also think for a first version it should be simple (you can always add on extra functionality later)

> Would you want to have them at the top of the file like this, or interspersed inside a markdown note closer to where the information is written?

The top doesn't seem great, but it stays within the "frontmatter" standard, and makes it easy for other apps to reuse the questions and answers, i believe this fits in with the foam methodology.

Having it with the content is nice for context, but i don't have much idea on what this would look like.
- How is it rendered?
- Do we hide it in preview?
- How can we parse it out?
- Does this mean it's now foam specific (rather than frontmatter which can be parsed by anyone)

**Comment by fmagin** [comment]
I personally use Anki myself and am also quite interested in combining my note taking and my flashcards. 

I feel like this issue starts with some really complicated solutions, instead of talking about some simpler ones first:
Anki can import typically table formats like CSV/TSV. So as long as you can export a foam note to an appropriate csv you can import it into Anki as an Anki note. This is both available as a GUI option and by simply calling `anki cards.csv` which starts Anki and opens the import dialog with that CSV file.

> it would be nice not to duplicate the Anki questions (if they already exist on Anki don’t add again)
the import feature I am talking about has an option if the first field of a row in the CSV matches an existing card. You can either update the existing card with the new field data (and keep the learning progress!), ignore the card, or add a new card.

So my suggestion would be:
Foam could just support exporting certain metadata to certain formats in general, in this case this could be the `anki` field in the frontmatter metadata that is already in a form that can be exported to a CSV as one Anki note per row (an [Anki card](https://apps.ankiweb.net/docs/manual20.html#card-types) is not the same as an [Anki note](https://apps.ankiweb.net/docs/manual20.html#note-types). Though at this point it doesn't even feel like you are doing anything Foam related anymore. So maybe even make this a separate extension that just generates Anki notes from Markdown metadata. 

If the goal is just to support specific card types it would be possible to create Anki note types that contain fields with Foam related metadata, e.g. the Foam note the flashcard came from. If the first field is designed with this in mind it could then be used to make sure Foam exported cards don't interfer with 


The RemNote syntax looks neat, but I feel like this would introduce an absurd amount of complexity because you would have to extend the markdown parser itself. The metadata approach seems a lot simpler.

I expect this to be a lot simpler than dealing with the Anki API itself and to be enough for many users.

**Comment by jasonwilliams** [comment]
@fmagin i agree with most of what you've said. 
The more i think about it the more i think Anki functionality should live in it's own VSCode plugin, I've made good progress on this and will hopefully have something to show in a week or so.

**Comment by jsjoeio** [comment]
> Also no import/export is needed, i've been able to bridge VSCode directly to Anki, so you can just run a command on a Markdown file and it's straight in there.

🤯 Oh man, that's exciting to hear. 

> I've made good progress on this and will hopefully have something to show in a week or so.

Sweet! Looking forward to checking it out!

**Comment by jasonwilliams** [comment]
@jsjoeio https://marketplace.visualstudio.com/items?itemName=jasew.anki try it and let me know, it may be buggy but should work well enough

**Comment by jsjoeio** [comment]
Woot woot! Will do. Props for coming up with something so quickly!

**Comment by jasonwilliams** [comment]
I think this issue can be closed now that https://marketplace.visualstudio.com/items?itemName=jasew.anki is available.
If there's a link of extensions this can be used with maybe it can be added there.
