### ISSUE TITLE
Broken Wiki-links

### ISSUE THREAD

**Issue by dakenblack** [foambubble/foam#217]
Hi, 

I've got an issue with the wiki-links feature. See screenshot, I've linked to 2 files within the same directory but vscode isn't generating the reference list at the bottom of the page when I save. It works for some pages (a minority) but not all. Unfortunately I can't identify any pattern to these failures, i.e. I don't know what's different about the pages that work from the ones that don't.

Oddly enough the "show graph" feature of markdown links seems to recognize the links.

![Works](https://user-images.githubusercontent.com/11382198/89724881-038a8200-da4c-11ea-871a-7611f2805046.png)

![Doesn't work](https://user-images.githubusercontent.com/11382198/89724877-fbcadd80-da4b-11ea-82df-c7ee07f959db.png)

You can also see the extensions I have enabled in the screenshot, I'm running this on a windows computer let me know if you need any other information.

Thanks for this great project!

**Comment by zbw8388** [comment]
It seems like there's an issue with capitalized file name. Try rename your notes to "aws.md" and "tensorflow.md" and save again.

"show graph" is actually provided by another extension, so there's inconsistency between two extensions.

**Comment by dakenblack** [comment]
Righto,
That worked! I should've picked that up thanks.

So there is an issue with filenames with capital letters.

**Comment by jevakallio** [comment]
@dakenblack @zbw8388 correct, this is documented in https://foambubble.github.io/foam/link-formatting-and-autocompletion

We are going to fix this, but for stupid reasons it's a bit hard to fix for one segment of users who prefer their links to match file cases literally, without breaking it for others who expect the links to be slugified to `lower-dash-case` format, which is what Foam's initial version shipped with.

It will eventually be fixed by when we implement https://github.com/foambubble/rfcs/pull/3
