### ISSUE TITLE
Wiki-links MD compatibility generator spacing from end of content

### ISSUE THREAD

**Issue by ShaunaGordon** [foambubble/foam#226]
**Current behavior:** When Markdown-compatible links are generated and added to the bottom of the document, they add only one additional newline. When VSCode is using application defaults (no newline on save), this results in only one newline between the content and the links, which Markdown doesn't interpret as a new paragraph/element, resulting in the links getting "attached" to the content.

**Expected behavior:** The links block should always include an additional newline to create at least one blank line between the end of the content and the links block so that it's always separate from the content.

**Note:** The current behavior is affected by VSCode's newline-on-save setting. VSCode defaults the "add newline to end of files on save" setting to `false`, which results in the above current behavior. However, when this setting is set to `true`, the expected behavior is observed. This feature should not be dependent on this VSCode setting to work properly and should have the expected behavior at all times to avoid getting tangled into the content.

**Comment by anku255** [comment]
@jevakallio  I am working on it. I have found some issues already. Working on a fix.

**Comment by anku255** [comment]
@jevakallio Should there always be **two newlines** between the end of the content and the start of link references? 

Consider the 3 cases:

**Case 1**

```markdown
1. Some content...
```

**Case 2**

```markdown
1. Some content...
2.
```

**Case 3**


```markdown
1. Some content...
2.
3.
```

For all the three cases, the output should be - 

```markdown
1. Some content...
2.
3.
[//begin]: # "Autogenerated link references for markdown compatibility"
```

Is this the expected Behaviour?

**Comment by jevakallio** [comment]
There should always be exactly one blank line (so, two **newline characters**) between the end of content and beginning of the link reference block, like so:

```md
Some content...

[//begin]: # "Autogenerated link references for markdown compatibility"
```

Which, escaped, would look like this, assuming the EOL character is a line feed character, `\n`:
```md
Some content...\n\n[//begin]: # "Autogenerated link references for markdown compatibility"
```

And like, this, if the EOL character is a CR+LF sequence:

```md
Some content...\r\n\r\n[//begin]: # "Autogenerated link references for markdown compatibility"
```

For user friendliness, it might be preferable for there two be two blank lines (so, three newline characters) so people have more space to start new content without having to insert another newline, but since this conflicts with common markdown formatter tools like Prettier, which remove subsequent newline characters, it's somewhat impractical.
