### ISSUE TITLE
Install procedure enables Gray Matter for all file types

### ISSUE THREAD

**Issue by tlbtlbtlb** [foambubble/foam#243]
After installing foam, I found that all my syntax highlighting in other workspaces was gone and all my source code was black and white. It turned out to be because installing the 'recommended extensions' enables [Gray Matter](https://github.com/philipbelesky/gray-matter) for all file types, when it's only appropriate for markdown.

It's due to this line: https://github.com/foambubble/foam-template/blob/master/.vscode/extensions.json#L23

I think Gray Matter isn't really suitable for a recommended extension, since it's a pervasive change in UI for all workspaces and file types.

**Comment by vitaly-pevgonen** [comment]
https://github.com/foambubble/foam-template/blob/21605350b458d22f3c37f739809427476530d845/.vscode/settings.json#L6 enables this extension only for current workspace. When I open another workspace (in another window), it uses theme that I have configured globally.

Does VSCode use theme that you expect, if you open another window?

What theme is configured in your user settings (Preferences: Open user settings command, Workbench -> Appearance -> Color theme)?

**Comment by jevakallio** [comment]
@tlbtlbtlb as @vitaly-pevgonen said, this theme should only apply to a "Foam-enabled workspace", namely a VSCode session where either the `.vscode/settings.json` or a `.code-workspace` file specifies that theme.

If this is not how it works for you, please reopen the issue! Only closing it for housekeeping as, if this is behaving as expected, it's by design.
