### ISSUE TITLE
Ability to create a heading with a new wikilink

### ISSUE THREAD

**Issue by Spectrem12** [foambubble/foam#279]
When creating a link to a file that does not exit, similar to this: [[example]] 

It would be nice to be able to create headings within that file when the link is created.

EX: `[[example]](#foobar)`
Would create a file called example.md with the following inside of it
```
# example
## foobar
```

As well, when creating something like 

`[example](./../my-example.md)`

The link does not populate in the auto generate link references at the bottom of the page.

**Comment by ingalless** [comment]
@Spectrem12 Great suggestion! Am I to understand there are two issues here? (just in the interest of cleaning things up)

**1. Feature**
It would be nice to be able to create headings within that file when the link is created.

EX: [[example]](#foobar)
Would create a file called example.md with the following inside of it
```
# example
## foobar
```
**2. Bug**
As well, when creating something like

[example](./../my-example.md)

The link does not populate in the auto generate link references at the bottom of the page.

**Comment by Spectrem12** [comment]
I think you are correct, but I think since you didnt wrap the example in ``` it doesnt literate exactly what you mean.
But yes, you are correct! I think ultimately, the want is to be able to link to headings within a new page when creating wikilinks.

I just discovered another bug or rather.. an unexpected behavior that is directly related to this.

If you create a heading with a wikilink to another page then the links with the single bracket do not function correctly.

![image](https://user-images.githubusercontent.com/2810347/95630415-68ac2500-0a47-11eb-87d4-d69886b98e02.png)

![image](https://user-images.githubusercontent.com/2810347/95630451-76fa4100-0a47-11eb-8da9-27fa21733fda.png)

**Comment by riccardoferretti** [comment]
good point @Spectrem12 - I think this is a bit tricky because TOC generation is provided by Markdown All-in-one, which per se doesn't support wikilinks. 
Support for wikilinks is added via Markdown Notes, a different plugin.

So the case you are describing falls exactly in the cracks between the two plugins..

Could you file an issue with Markdown All-in-one and see if they are open to addressing it?
(basically it feels like they should escape `[[` and `]]` from the text in the TOC.

I also wonder whether this same situation would cause problems in case of having a regular link (`[text](http://to.url/path)`) in a heading
