### ISSUE TITLE
["BUG"] Show Graph produces a graph with a black background. Cannot see names of notes.

### ISSUE THREAD

**Issue by lucabol** [foambubble/foam#318]
See the below picture. Copied the template and created a few connected notes. 'Show graph' displays a graph with a black background. Hovering the mouse over a node shows the name in white foreground, black background. I am using the standard style in the template.

![image](https://user-images.githubusercontent.com/1370774/98368311-6da8c800-2037-11eb-998b-8619ad9a630f.png)

**Comment by jessebett** [comment]
I also have this issue.

**Comment by riccardoferretti** [comment]
the graph currently doesn't follow the color scheme of vscode, this will be addressed soon :)

**Comment by lucabol** [comment]
Do you mean that I need to choose a vscode color scheme where the foreground color for text is white to be able to see it?

**Comment by riccardoferretti** [comment]
Sorry @lucabol, you were describing two issues and I only addressed one. Here they are:
1. the graph colors right now are not configurable and don't follow the vscode theme - that can be annoying just because of the contrast
2. currently the graph doesn't show labels, this is regardless of the color scheme and has been addressed in #310, which will is scheduled to be released on Monday

Basically, as of next week, you will be able to see labels in the graph, but the color scheme will still be limited to the dark one you see. 
Next in the graph is addressing the theme, as well as making some elements more configurable.

I hope this clarifies.

I created #322 to track theming the graph (point n.1), so I will close this issue (as point n.2 has been done), but feel free to reopen if you think I haven't addressed something correctly.

**Comment by lucabol** [comment]
Perfectly clear. Thank you for following up.
