### ISSUE TITLE
["BUG"] No foam commands working with v0.6

### ISSUE THREAD

**Issue by fmagin** [foambubble/foam#363]
**Describe the bug**
All the Foam commands fail with e.g. `Command 'Foam: Show graph' resulted in an error (command 'foam-vscode.show-graph' not found)` and analogous for the other commands in v0.6

They still appear in the `Command Palette`, so they are loaded in some way, but the actual command doesn't seem to be properly setup.

**Affected package**
- `foam-vscode`

**To Reproduce**
This might be something with my setup again, will try to track this down if someone can give me some pointers.

**Additional context**
Maybe this is related to frontmatter formatting issues again?

**Comment by riccardoferretti** [comment]
The fact that all the commands fail makes me think there is an issue with the bootstrapping phase of the extension.
I noticed in the code we would simply log such a problem (see https://github.com/foambubble/foam/blob/d054e19eae517408696dc6a6b5edb4c26c929e4e/packages/foam-vscode/src/extension.ts#L53), we should instead use `window.showErrorMessage` to present it to the user.
As I wanted to have a new release today or tomorrow, I will add this change so that you can more easily find out if that's the problem, and what the cause is.

**Comment by riccardoferretti** [comment]
removing milestone as what I am doing for this milestone is not a fix to the problem, but a tool for better reporting/investigation

**Comment by b2m9** [comment]
Same problem here. I'll provide some system information:

- VSCode 1.51.1
- Electron: 9.3.4
- Node: 12.14.1
- OS: Manjaro Linux, kernel 5.9.10

**Comment by riccardoferretti** [comment]
There seems to be a sporadic linking issue in 0.6.0, which I applied a fix for in 0.7.0 - @fmagin @b2m9 can you update and check if the problem is still there?

**Comment by fmagin** [comment]
Yes, the commands work again!
For what it's worth, I am using Arch Linux which should have quite similar package versions to Manjaro, so maybe this was related. I think another person I know on Manjaro also had this issue. So it might not have been that sporadic after all, but it seems to be fixed now. Thanks!

**Comment by b2m9** [comment]
Just in case other Linux users find this via Google:

If you use **Code OSS** or **VSCodium** you won't see the new versions of the Foam extension because they're **not** using the Microsoft Marketplace anymore by default. Instead, they use [OpenVSX](https://open-vsx.org/extension/foam/foam-vscode). The extension on OpenVSX is not updated at the moment. From what I can tell it's also not clear whether it will be a reliable update channel in the future.

To switch back to the Microsoft Marketplace, follow [instructions on SO](https://stackoverflow.com/questions/64463768/cant-find-certain-extensions-in-code-ossopen-source-variant-of-visual-studio-c).

**Comment by riccardoferretti** [comment]
thanks @b2m9, we will release to OpenVSX too moving forward as well
