### ISSUE TITLE
Opening directory in VSCode caused theme to change from dark to light

### ISSUE THREAD

**Issue by phillijw** [foambubble/foam#37]
I cloned my template and opened it in VSCode. Since I was on an older version of VSCode it simultaneously asked me to upgrade to a newer version and install all the extensions. I chose to install the extensions first and it complained that my version was too old. Then it proceeded to change my theme to be light instead of dark. Then I clicked button to upgrade to a newer version and it reopened with light theme still enabled.

**Comment by jevakallio** [comment]
Hi Joe! 

Setting the theme is intentional, but it should be workspace specific. If you open another VS Code window in another project, it should be using whatever theme you were using before. If that's not the case, let me know. That could be a bug with an older version of VS Code.

You can change the theme with `Cmd+Shift+P` (Or `Ctrl+Shift+P` on PCs) "Change theme". The suggested Foam theme is Gray Matter, which comes in light and dark editions, but you can use whatever theme you like.
