### ISSUE TITLE
["BUG"] "Show Graph" command produced a black background without nodes

### ISSUE THREAD

**Issue by ysl2** [foambubble/foam#378]
**To Reproduce**
Reload VSCode and use `Foam: Show Graph` command.

**Screenshots**
There are some files in my repository but foam did't show these nodes.
![image](https://user-images.githubusercontent.com/39717545/100301753-cda9e300-2fd3-11eb-90ee-b7e4dced6d1a.png)

**Supplement**
Sometimes after linking a file to another, and reuse the command, both the two files' nodes will appear. 
Or type any words in a file, and reuse the command, the file's node will also appear.
But if you reload VSCode and reuse the command, all the nodes will disappear again.
It's not stable and I'm not sure when and why this bug will appear, as if it will only show the nodes which has been modifed. Once VSCode is reloaded, all the files will be regarded as "not modified".
By the way, all the links in my repository are regular markdown links, not wikilinks.

This is the contrast between `Foam: Show Graph` command (left) and `Markdown Links: Show Graph` command (right) :
![image](https://user-images.githubusercontent.com/39717545/100303362-48c0c880-2fd7-11eb-899e-ae66de0e5efe.png)

**Test Environment**
Windows 10 version 1909
Plugin version 0.7.0

**Comment by riccardoferretti** [comment]
@ysl970629 are the files linked using `[[wikilinks]]` or `[regular links](path/to/file)`?

**Comment by ysl970629** [comment]
> @ysl970629 are the files linked using `[[wikilinks]]` or `[regular links](path/to/file)`?

`[regular links](path/to/file)`, and I use relative path : 

```
# file1

[file2](../test/file2.md)
```

**Comment by zcysxy** [comment]
I experienced the same, after updating to 0.7

**Comment by ysl970629** [comment]
I thought It was just me, now I'm not feel lonely. @zcysxy 
And just now I found I can't preview wikilinks without references : 
![image](https://user-images.githubusercontent.com/39717545/100415894-218df800-30b8-11eb-99f7-f9845fc2b634.png)
As you see , the second link can't be opened

**Comment by riccardoferretti** [comment]
> [regular links](path/to/file), and I use relative path :

This will be supported in Foam soon and is tracked in #299 

> I can't open wikilinks without references in preview mode

That would be expected because of the way the preview currently work (basically it uses definitions to navigate links, it doesn't find one, so you can't navigate)

In 0.7.1 (which will go out today) there will be more logging, which can help us debug this issue more easily.

**Comment by ysl970629** [comment]
> > [regular links](path/to/file), and I use relative path :
> 
> This will be supported in Foam soon and is tracked in #299 

OK, thank you :-)
For the regular links in version 0.6.0, `Foam: Show Graph` command will create a graph with only nodes and no edges. The nodes were exist. However in version 0.7.0, the nodes are disappeared.

I think there is a hint that might helps you: in windows platform,  when you are copying a file's path to clipboard, the file path is separated by backslashes `\`, not `/`. @riccardoferretti

**Comment by ysl970629** [comment]
I set `log.level` to `debug`, and reload vscode, then I got this infomation in output area : 
```
Foam Logging: debug
[info - 上午9:35:16] Starting Foam
[debug - 上午9:35:16] Glob patterns
{
  "includeGlobs": [
    "f:\\20-foam_document/**/*\\.(md|mdx|markdown)"
  ],
  "ignoreGlobs": [
    "f:\\20-foam_document/**/.vscode/**/*",
    "f:\\20-foam_document/**/_layouts/**/*",
    "f:\\20-foam_document/**/_site/**/*",
    "f:\\20-foam_document/**/node_modules/**/*"
  ]
}
[info - 上午9:35:17] Loaded 0 notes
```
But in fact there are many files in my workspace folder...
![image](https://user-images.githubusercontent.com/39717545/100491385-f362f380-315d-11eb-8139-0a97a3807cbf.png)

**Comment by riccardoferretti** [comment]
@zcysxy Can you also share your logs please?
@ysl970629 does this happen to you with the standard foam-template?

**Comment by ysl970629** [comment]
Yes, my repository came from foam-template.
Just now I used `git clone` to download a new foam-template and I got same result : 
![image](https://user-images.githubusercontent.com/39717545/100509206-e4556300-31a8-11eb-8304-10a1f7d93b5f.png)
```
Foam Logging: debug
[info - 下午6:34:53] Starting Foam
[debug - 下午6:34:53] Glob patterns
{
  "includeGlobs": [
    "c:\\Users\\YSL\\Desktop\\foam-template/**/*\\.(md|mdx|markdown)"
  ],
  "ignoreGlobs": [
    "c:\\Users\\YSL\\Desktop\\foam-template/**/.vscode/**/*",
    "c:\\Users\\YSL\\Desktop\\foam-template/**/_layouts/**/*",
    "c:\\Users\\YSL\\Desktop\\foam-template/**/_site/**/*",
    "c:\\Users\\YSL\\Desktop\\foam-template/**/node_modules/**/*"
  ]
}
[info - 下午6:34:53] Loaded 0 notes
```

**Comment by riccardoferretti** [comment]
I wonder if it's related to windows path delimiters, I will look more into it

**Comment by ysl970629** [comment]
In windows, file path format like this (please pay attention to the backslash) : 
![image](https://user-images.githubusercontent.com/39717545/100514341-ce4aa100-31ae-11eb-92b6-08063d76bf09.png)

And I once opened a related issue for another vscode plugin several days ago, this may help you : 
https://github.com/mathiassoeholm/markdown-link-updater/issues/1

**Comment by BenjaminMuinga001** [comment]
Sent from my Huawei phone-------- Original message --------From: Riccardo <notifications@github.com>Date: Fri, Nov 27, 2020, 12:44 PMTo: foambubble/foam <foam@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [foambubble/foam] ["BUG"] "Show Graph" command produced a black background without nodes (#378)

regular links, and I use relative path :

This will be supported in Foam soon and is tracked in #299

I can't open wikilinks without references in preview mode

That would be expected because of the way the preview currently work (basically it uses definitions to navigate links, it doesn't find one, so you can't navigate)
In 0.7.1 (which will go out today) there will be more logging, which can help us debug this issue more easily.

**Comment by BenjaminMuinga001** [comment]
Sent from my Huawei phone-------- Original message --------From: Riccardo <notifications@github.com>Date: Fri, Nov 27, 2020, 12:44 PMTo: foambubble/foam <foam@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [foambubble/foam] ["BUG"] "Show Graph" command produced a black background without nodes (#378)

regular links, and I use relative path :

This will be supported in Foam soon and is tracked in #299

I can't open wikilinks without references in preview mode

That would be expected because of the way the preview currently work (basically it uses definitions to navigate links, it doesn't find one, so you can't navigate)
In 0.7.1 (which will go out today) there will be more logging, which can help us debug this issue more easily.

**Comment by BenjaminMuinga001** [comment]
Sent from my Huawei phone-------- Original message --------From: ‪‪‪Benjamin Lawrence‬‬‬ <benjaminmuinga001@gmail.com>Date: Sat, Nov 28, 2020, 5:34 PMTo: foambubble/foam <reply@reply.github.com>, Riccardo <notifications@github.com>, foambubble/foam <foam@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re:[foambubble/foam] ["BUG"] "Show Graph" command produced a black background without nodes (#378)Sent from my Huawei phone-------- Original message --------From: Riccardo <notifications@github.com>Date: Fri, Nov 27, 2020, 12:44 PMTo: foambubble/foam <foam@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [foambubble/foam] ["BUG"] "Show Graph" command produced a black background without nodes (#378)

regular links, and I use relative path :

This will be supported in Foam soon and is tracked in #299

I can't open wikilinks without references in preview mode

That would be expected because of the way the preview currently work (basically it uses definitions to navigate links, it doesn't find one, so you can't navigate)
In 0.7.1 (which will go out today) there will be more logging, which can help us debug this issue more easily.

**Comment by zcysxy** [comment]
@riccardoferretti Where is the log 😅, sorry I'm not a developer haha. Now the situation for me is the graph shows up again, but the node (and connected nodes) for a file only shows in the graph after I re-save it.

And yes, my workspace's path contains a special symbol "&".

And since my files' names have many symbols, spaces and capital letters in them, and I'm using lots of piped links as well as heading links like `[[page#heading]]`, so maybe my log file will barely help 😅.

**Comment by riccardoferretti** [comment]
@zcysxy no worries :) here it is

![image](https://user-images.githubusercontent.com/457005/100521402-b91c4500-31a3-11eb-9851-a7b573e29d5b.png)

if you don't see this bar, press ``` ctrl+` ```

**Comment by ysl970629** [comment]
@zcysxy 
Hello, if you want to print logs, please follow these steps : 
1. Add these words in `yourWorkspaceFolder/.vscode/setting.json` : 
```
"foam.logging.level": "debug",
```
2. press `ctrl+`` to open “OUTPUT” area.
3. reload VSCode and paste the contents in “OPTPUT” area here.

**Comment by ysl970629** [comment]
@riccardoferretti This morning I tried to back to version 0.6.0, and I found the "Show Graph" command runs normally, and the link references will be created by foam automatically.
![image](https://user-images.githubusercontent.com/39717545/100529552-c1b46000-3223-11eb-8cd7-37d0f3e11f91.png)

**Comment by zcysxy** [comment]
@riccardoferretti @ysl970629 Thanks for the help and sorry for the late reply! I only opened two files to generate the log. Tell me if you want me to test more!

[foam log.txt](https://github.com/foambubble/foam/files/5621516/foam.log.txt)

**Comment by JonasSchatz** [comment]
I experienced the same problem and wanted to recreate it. It might actually not be an issue with Foam, but rather VS Code or force-graph. This might be a related issue: https://github.com/microsoft/vscode/issues/112396

**Comment by riccardoferretti** [comment]
@ysl2 can you test with 0.7.4, which was just released?

**Comment by zcysxy** [comment]
@riccardoferretti Everything is back to normal for me. Thanks for your work!

**Comment by riccardoferretti** [comment]
Great to hear!
