### ISSUE TITLE
Saving a file removes the graph edge in foam graph. 

### ISSUE THREAD

**Issue by WoutV** [foambubble/foam#393]
- Foam version: `0.7.2`
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes | No

**Summary**
Saving a file removes incoming graph edges

**Steps to reproduce**
1. create a new `[[link]]` in a file `origin.md`
2. cmd-click to go to new file `link.md`
3. save new file
Result: the link between `origin` and `link` in the foam graph disappears.

**Comment by SanketDG** [comment]
I can reproduce this too.

**Comment by AndrewNatoli** [comment]
Sharing some hopefully useful additional info:

- Create a new `[[link]]` in `origin.md` - Don't save
- When you cmd+click the link, the new file is created and `origin.md`'s link references get updated.
- The link appears on the graph.
- Go to the new `link.md` and save the file. The link disappears on the graph.
- The link returns when you save `origin.md` again.

The same happens when you _do_ save `origin.md` before clicking `[[link]]`. In both cases you need to re-save `origin.md` after saving `link.md`.

**Comment by WoutV** [comment]
This mostly creates issues when you are several links deep. Saving 20 files
that didn't change is a hassle.

**Comment by csuriano23** [comment]
I can reproduce this too

**Comment by AndrewNatoli** [comment]
Trying to debug a bit.. it looks like this is what's going on in `note-graph.ts:setNote`...

1. When you create the new `[[link]]` in `origin.md`, two things happen:
  - A node is created on the graph for `link.md`. Its `links` is empty as it has no outbound links.
  - The graph node for `origin.md` is recreated with `links` including `link.md`, thus the graph connections.
2. When you edit and save `link.md`...
  - The `link.md` node is recreated. In the process its edges are cleared.

Then in `datavis.ts:generateGraphData()`, `origin.md` does not have any outgoing links detected anymore.
