### ISSUE TITLE
Does foam support local folders?

### ISSUE THREAD

**Issue by sahil48** [foambubble/foam#4]
Can foam workspaces be set up locally without github?

**Comment by jevakallio** [comment]
@sahil48 yes! Easiest way to get started is to go to https://github.com/foambubble/foam-template and **Download as ZIP** instead of "Use this template". 

You can then sync it up to Dropbox or just keep it locally if you want.

The other half of Foam is static site publishing. For the time being if you don't use GitHub and GitHub pages you're on your own as to how and where to deploy that.

**Comment by jevakallio** [comment]
Updated this in the [getting started](https://foambubble.github.io/foam#getting-started) documentation
