### ISSUE TITLE
Foam disables word based suggestions in markdown files

### ISSUE THREAD

**Issue by bpugh** [foambubble/foam#415]
- Foam version: 0.7.6
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**

It seems having the Foam vscode extension installed disables or breaks word based suggestions in markdown files even with `"editor.wordBasedSuggestions": true`.

I verified with a fresh install of vscode with only the foam extension installed and when the extension is enabled I don't get any word based suggestions but as soon as I disabled the extension and reload vscode then the suggestions are working again. 

I also noticed that suggestions work if the extension is installed but I'm not working in a directory with a `foam.json`

Is this intentional? If not, I'd be willing to investigate if someone could point me in the direction of where to start looking in the codebase.

**Comment by riccardoferretti** [comment]
hi @bpugh thanks for reporting this and volunteering to look into it. It is definitely not intentional.

The place to start looking would be `packages/foam-vscode`.
To set your environment up, take a look at https://github.com/foambubble/foam/blob/master/docs/contribution-guide.md
The only place where I believe (off the top of my head) we interact with the vscode suggestion system is in `packages/foam-vscode/src/features/open-dated-note.ts`, might be a good place to start (cc @ingalless as he worked on it).

Let me know if you need anything

**Comment by bpugh** [comment]
Thanks for the advice! I got the extension building and running locally and confirmed the issue is fixed by commenting out the two calls to `registerCompletionItemProvider` here: https://github.com/foambubble/foam/blob/master/packages/foam-vscode/src/features/open-dated-note.ts#L218-L224

Just have to figure out the solution now. I'll start digging through the vscode documentation to try figure out exactly whats happening.
