### ISSUE TITLE
Possible to include the link reference in the published version? 

### ISSUE THREAD

**Issue by jarodise** [foambubble/foam#45]
Is it possible to include the link reference in the Github pages rendered/published version? 

This would be super helpful for digital gardeners.

**Comment by jevakallio** [comment]
@jarodise do you mean the link reference fields, like this?

```md
[//begin]: # "Autogenerated link references for markdown compatibility"
[on-change]: on-change "onChange"
[//end]: # "Autogenerated link references"
```

When I implement [[Materialized Backlinks](https://foambubble.github.io/foam/materialized-backlinks)], I could trivially put in an option to generate "forward links" as well, if that would be useful?

**Comment by jarodise** [comment]
Yeah, basically, the idea is to able to create a static site where I can publish my notes and showcase the linkage between the notes, similar to a public Roam database, where the linked pages shown below the note. This kind of site is nowadays referred as "Digital Gardens". For your reference, you can check out this Github repo: https://github.com/MaggieAppleton/digital-gardeners

**Comment by khimaros** [comment]
@jevakallio -- do you already have thoughts on how backlinks should be handled in Foam? do you already know how you want them to appear in the markdown or in the published HTML?

**Comment by riccardoferretti** [comment]
There are various paths we can follow, here is what comes to mind:
The easiest approach would be to add a command that actually writes the backlinks in the files. this approach is in line with the wikilink definition approach, so it could follow the same pattern (including presence in the janitor)

I think a better approach would be to investigate whether it's possible in jekyll to have a sort of build step, which we would use to generate the backlinks from there (via the Foam model).
If this route turns out to work, we could even have the wikilink definitions be part of it (which means that you wouldn't need to use them unless you were publishing directly to GH web UI).

This is not at the top of the roadmap (which I am overdue to share an update of), but will be soon-ish.
In the meantime, if someone wants to take a stab at approach n.2 I can provide support.

**Comment by riccardoferretti** [comment]
a quick search yielded this: https://jekyllrb.com/docs/rendering-process/
sounds like exactly what we need.
I am not familiar with Jekyll, but someone with more experience might be able to create a plugin or something to interface with Foam and generate the relevant data.

**Comment by wcerfgba** [comment]
There are a few projects linked from https://github.com/MaggieAppleton/digital-gardeners which provide backlinks in Jekyll, probably we could just lift some code from one of these? Here are some examples:

* https://github.com/maximevaillancourt/digital-garden-jekyll-template/blob/master/_plugins/bidirectional_links_generator.rb
* https://github.com/raghuveerdotnet/simply-jekyll/blob/master/_includes/backlinks.html

**Comment by khimaros** [comment]
was this fixed by a PR or decided not to fix?

**Comment by riccardoferretti** [comment]
This is something that we don't support in Foam core, but is left to be implemented to the theme used for publishing
