### ISSUE TITLE
User Selectable Tag Character

### ISSUE THREAD

**Issue by njnygaard** [foambubble/foam#456]
I enjoy using a [Markdown Linter](https://github.com/DavidAnson/markdownlint) in VS Code.
It comes with a list of rules.
[One of which](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md018---no-space-after-hash-on-atx-style-heading) stipulates that `#interesting` is an error.
The rationale is that an article title should be of the form `# Title` so `#Title` is an error.

I agree with the rationale and would like the ability to set a setting for my 'tag character'.
I'd like to implement this myself, but I'd like feedback before I start to determine if this is desirable or already implemented.

**Comment by njnygaard** [comment]
For color, this can be bypassed by creating the file `.markdownlint.json` with the contents:
```json
{
  "MD018": false
}
```
But I don't want to disable the whole rule for something that could grow to a very large project.

**Comment by riccardoferretti** [comment]
hi @njnygaard, thanks for sharing the Linter link, I wasn't aware of it.

We have no plans of making the tag character configurable atm, it could be considered if there were wider interest, it feels (to me) like a specific use case that can easily be worked around on the linter side.

I wonder if the issue should be addressed by the linter, as far as I know `#tags` are pretty standard in markdown, it really feels like something the linter should in some way support.
Maybe the linter could check if the `#interesting` happens on the first character? and otherwise interpret it as a tag?

Not sure, have you tried checking with them too?

**Comment by SanketDG** [comment]
> as far as I know `#tags` are pretty standard in markdown

Just to make sure everyone is on the same page, `#tags` is not part of any major Markdown spec. OTOH, It's a widespread convention to use it in front-matter for every SSG out there.

So supporting `#tags` will be slightly against (if not additive to) the spec (also if we want do future things with tags)

It makes sense from a spec perspective to lint `#Title`, but then you can disable it as above.

Also, any markdown linter should ignore front matter, since it's not markdown anyway, so I assume tags would work there for any markdown linter.

**Comment by riccardoferretti** [comment]
> Just to make sure everyone is on the same page, #tags is not part of any major Markdown spec. OTOH, It's a widespread convention to use it in front-matter for every SSG out there.

You are right, I should be more specific when I say things like these, it's not the first time it's causing confusion 😅 
"Pretty standard" referred to "common use" (I know, ambiguous) instead of "defined in most of the standards".
Thanks for the clarification.

> any markdown linter should ignore front matter, since it's not markdown anyway

I believe this is in line with my general point: I don't believe front matter is defined in major markdown specs (I knew it was not in [commonmark](https://commonmark.org/), I was actually surprised it isn't part of the [gh specs](https://github.github.com/gfm/) either), although we could say it's "fairly common" to use it to define properties in a markdown file.
If a linter is complaining about the front matter format I don't think we should provide flexible front matter strings to make the linter happy because front matter is not official markdown - it's ok for Foam to have a POV.

I realize this is not black and white (front matter is probably "more common" than `#tag`, maybe?), but I think somewhere we need to draw the line - so I would like to understand how common this specific issue is before jumping to adding the configuration option.

I also really like your alternative approach of putting tags in front matter, which is super simple. It might not satisfy the case when a tag need to be in the context of some text, but it does go a long way.

**Comment by njnygaard** [comment]
Thanks for the feedback.
For what it is worth, I have tried to understand the linting rules more thoroughly and I believe that this isn't a valid issue.
The linter supports front matter, so @SanketDG your suggestion will work well for document-wide tags.
Also @riccardoferretti, I neglected to test tags in the actual flow of text.
I jumped the gun and flagged this issue when I noticed the linter complaining about tags at the beginning of a line.
Because tags should really be contextual in nature, I think the current behavior in foam and the linter is correct.
![image](https://user-images.githubusercontent.com/4606342/105797608-8f865c80-5f4d-11eb-9295-df644028ffe4.png)
You can see all three cases here. I'm documenting them here for posterity.
I can close this or you can.
Thanks for this project, I'm excited to use it more.

**Comment by riccardoferretti** [comment]
Great! Glad it worked out!
