### ISSUE TITLE
Add support for reStructuredText

### ISSUE THREAD

**Issue by mcallaway** [foambubble/foam#474]
Is it possible to support reStructuredText in addition to Markdown?

**Comment by mcallaway** [comment]
My goal here is to make a "second brain" that works with Sphinx too. But I've since found that Sphinx supports Markdown, so I can get what I'm after. I'm not sure if .rst offers interest to others, but I chose it over Markdown after reading discussions like this one:

https://eli.thegreenplace.net/2017/restructuredtext-vs-markdown-for-technical-documentation/

**Comment by riccardoferretti** [comment]
Technically speaking, adding support for reStructuredText would be fairly straightforward. if you want to play with the idea I would suggest looking at `markdown-provider.ts`, adding a `reST-provider.ts` and take it from there.

Adding a second file format would be quite an undertaking later on though, because it would require maintaining it in future changes to the model, the features, ... - so I am very hesitant to do it at this stage unless there is good reason to do so, this is not high on the priority list / roadmap for Foam and might slow us down as we progress on our priorities.

I don't know much about reST to be honest, so I don't feel I am in a position to gauge interest and utility for supporting it.

**Comment by mcallaway** [comment]
Thank you for the response. I understand. I'll continue to work on integrating with Sphinx, for example producing tables-of-contents, in order to produce attractive output (book-like).

**Comment by ankostis** [comment]
Just to note that the nesting capability of reST is important when interfacing with 3rdp systems & libraries, so you are forced sometimes to maintain in your garden content in this language (e.g. [Hovercraft](https://hovercraft.readthedocs.io/en/latest/) for _prezi-like_ presentations).
