### ISSUE TITLE
Font style issue after typing "fi"

### ISSUE THREAD

**Issue by technoweenie** [foambubble/foam#49]
I'm experiencing this unexpected font style change after typing "fi." It shrinks a bit. It only happens in my Foam workspace. I don't see it when I open one of my coding projects or start a new workspace from a blank repo.

<img width="89" alt="Screen Shot 2020-07-03 at 9 25 33 AM" src="https://user-images.githubusercontent.com/21/86482464-33d55700-bd0f-11ea-8c98-ea0611aba937.png">

I have already tried disabling the Foam-specific extensions (the markdown and theme ones). Is anyone else seeing this?

**Comment by jevakallio** [comment]
@technoweenie oops! Turns out that we had `editor.fontLigatures` on in the settings.json of the foam-template project. Your font appears to have a `fi` [ligature](https://www.hanselman.com/blog/MonospacedProgrammingFontsWithLigatures.aspx#:~:text=Typographic%20ligatures%20are%20when%20multiple,your%20app%2C%20and%20your%20font.) which causes this effect.

I've just removed them from the default template here. Font-specific settings don't belong in the project template.

https://github.com/foambubble/foam-template/commit/d8083dbb7665459d31e93163614840e0b9c7eaba

Remove that line from your `.vscode/settings.json` and reload your workspace, and it should default your user settings (assuming font ligatures)
