### ISSUE TITLE
Broken link references being published to GitHub Pages?

### ISSUE THREAD

**Issue by caseyg** [foambubble/foam#51]
Any idea why my link references are getting committed and published to GitHub Pages? Aren't they supposed to only appear in VS Code for now?

(p.s. Foam is amazing!! Thank you.)

**GitHub Pages:**

<img width="815" alt="Screenshot 2020-07-04 at 7 56 38 AM" src="https://user-images.githubusercontent.com/462020/86511992-06021800-bdcc-11ea-93d9-a948ad793279.png">

**VS Code:**

<img width="944" alt="Screenshot 2020-07-04 at 7 56 53 AM" src="https://user-images.githubusercontent.com/462020/86511994-0a2e3580-bdcc-11ea-9732-c4f216cd6813.png">

**Web:**
https://cag.wiki/todo

**Github:**
https://github.com/caseyg/foam/blob/master/todo.md

**Comment by jevakallio** [comment]
I am no longer seeing these in the live site so looks like you got it fixed @caseyg!

The issue was that there was no new line between the last line of content and link reference definition list. Markdown specifically requires this.

However, I'm not sure how this occurred, as the foam-vscode plugin is supposed to ensure the newline is added. Could you give me the version of the extension you're using -- I have made fixes in this area in the past week, but if you downloaded today and are on 0.1.6+ this should not be an issue and needs to be investigated.

**Comment by jevakallio** [comment]
I couldn't replicate this issue, so going to assume that either this happened on old version of foam-vscode, or the update task didn't run at all.

Closing to clean up issues, please reopen if the issue persists!
