### ISSUE TITLE
Follow link via `Go to definition` command

### ISSUE THREAD

**Issue by maciejmatczak** [foambubble/foam#543]
With new functionality in https://github.com/foambubble/foam/pull/524, I uninstalled the https://marketplace.visualstudio.com/items?itemName=kortina.vscode-markdown-notes, but it seems the current implementation only supports a mouse click.

Hence a request - please add support for generic VS Code `Go to definition` action for wiki links. `Peek a definition` might also be handy.

Thanks

**Comment by JonasSprenger** [comment]
After playing with Vscode API, it seem that the command you (@maciejmatczak) are looking for is `Open Link` (`@command:editor.action.openLink`).
It's the same command as `ctrl + click`, implemented with `interface DocumentLinkProvider<T extends DocumentLink = DocumentLink>`.
https://github.com/foambubble/foam/blob/7412d518d7aeb00976bfbf7b517db62d78f692f7/packages/foam-vscode/src/features/document-link-provider.ts#L29

The main difference is than `Go to definition` target a specific range in the destination file, whereas `Open Link` open just the file (so don't move the cursor if the file is already open).

A similar functionality which can be interesting to implement is `Go to References`/`Peek References` (it seems to me it exactly the same) with a `ReferenceProvider`. It should be the same as the backlinks of the targeted note.

**Comment by maciejmatczak** [comment]
Markdown Notes mentions:
https://github.com/kortina/vscode-markdown-notes/blob/0ac9205ea909511b708d45cbca39c880688b5969/README.md#L19
> Markdown Notes provides syntax highlighting, auto-complete, Go to Definition (editor.action.revealDefinition), and Peek Definition (editor.action.peekDefinition) support for wiki-links to notes in a workspace.

Similar provider: https://github.com/kortina/vscode-markdown-notes/blob/0ac9205ea909511b708d45cbca39c880688b5969/src/MarkdownDefinitionProvider.ts

And I guess as definition is pretty much a language bases concept, it have to be supported by parser, right?

https://github.com/kortina/vscode-markdown-notes/blob/0ac9205ea909511b708d45cbca39c880688b5969/syntaxes/notes.tmLanguage.json#L11

**Comment by JonasSprenger** [comment]
Thanks for the resources.

Indeed we can use `Go to Definition`, maybe by targeting the first header of the note or the whole file (using the range field).
But I think it's not a good idea to keep both commands to follow links (`Open Link` and `Go to Definition`).
`Go to Definition` seems more appropriated because it's more language specific.

> And I guess as definition is pretty much a language bases concept, it have to be supported by parser, right?

If I understand the API correctly, no, it don't have to be supported by a parser. Just register a `DeclarationProvider`.
https://code.visualstudio.com/api/references/vscode-api?ref=hackernoon.com#DeclarationProvider

**Comment by JonasSprenger** [comment]
When implementing and testing the `Go to Definition` #724 , I find it less suitable for our use case.

- The call it's triggered on 'hover', so IMHO it's not adapted to create a new file if the link is a placeholder. Because it will necessarily happen inadvertently.
    - it is the same behavior as https://github.com/kortina/vscode-markdown-notes/blob/0ac9205ea909511b708d45cbca39c880688b5969/src/MarkdownDefinitionProvider.ts
- There is the possibility to use the `Open Link` command if the link doesn't exist and `Go to Definition` if it exist. But I don't thinks it's worth the increase of complexity for the user (two different commands for almost the same functionality).
- An alternative solution is to implement the `hover-feature` to have some of the benefits of `Go to Definition`.

**Comment by riccardoferretti** [comment]
Fixed by #821

**Comment by maciejmatczak** [comment]
Thank you @JonasSprenger, @riccardoferretti!
