### ISSUE TITLE
Wikilinks doesn't work inside frontmatter/yaml

### ISSUE THREAD

**Issue by danielarmengolaltayo** [foambubble/foam#557]
- Foam version: 0.12
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

That behavior was previously managed by the extension Markdown Notes, but once disabled and just relying on Foam extension, wikilinks do not work inside frontmatter/yaml.

The behavior is detected when disabling Markdown Notes, after the message for the release of v0.12: 
> "Also Foam finally provides document link navigation without the need for third party extensions, which means all your navigation is powered by one model."

I assume that this is the reason why wikilinks inside frontmatter/yaml do not appear in the backlinks panel.

**Comment by tabulon** [comment]
I would very much appreciate the ability to have links in YAML blocks (frontmatter or any subsequent YAML block).  

However, YAML doesn't have any link syntax. In fact, unless placed in quotes, the usual `[[wikilink]]` syntax has a entirely different meaning in YAML: A one element array which contains another -one element- array. 

Imho, it's preferable to keep YAML clean and valid, void of extra syntactic noise (which can be problematic for automated processing of YAML by other scripts that could choke on any special link syntax).

One way to achieve link functionality without abusing YAML syntax would be to treat all YAML scalars as *potential* implicit links, as I have recently [proposed][approach] on the Obsidian forum for the same topic... along with a plausible set of simple [implementation choices][implementation] .

This may sound awkward or even stupid at first... but you may be surprised... The rationale, as well as the gory details, are given on the two mentioned posts above (just replace the word "Obsidian" with "Foam" 😉)

For info: I am experimenting this scheme with the help of two generic **vscode plugins** readily available : 

- [Path Autocomplete] (by @`Mihai Vilcu`) which provides generic path completion.
- [Open File] (by `Frank Stuetzer`) which extracts a filepath from the current cursor position and than opens that file
 
Both have settings (which need to be teweaked) that allow : 

- working with markdown files and automatically adding/stripping the ".md" extension
- path lookups from multiple locations to find nearest match: absolute, current document's folder, workspace, workspace's src, defined search paths, etc.

This way, I can get them to work with plain link targets that behave almost like wikilinks (except for slug and whitespace behavior) without the need for specific syntax. 

Needless to say: currently, such implicit links are not officially recognized by the foam ecosystem (for backlinks and such).

Another remaining issue for me is the lack of a **visual hint** : I would really like those implicit links to be visually distinguishable when they correspond to an actually existing file/note.

___

[Open File]: https://marketplace.visualstudio.com/items?itemName=Fr43nk.seito-openfile
[Path Intellisense]: https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense
[Path Autocomplete]: https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete

[approach]: https://forum.obsidian.md/t/allow-links-in-yaml-front-matter-notion-like-databases-from-metadata-links-as-first-class-citizens/10052/23?u=tabulo

[implementation]: https://forum.obsidian.md/t/allow-links-in-yaml-front-matter-notion-like-databases-from-metadata-links-as-first-class-citizens/10052/23?u=tabulo

**Comment by danielarmengolaltayo** [comment]
Good point, I didn't take into consideration the conflict of the usual `[[wikilink]]` syntax with YAML syntax, thanks! I read your post on the Obsidian forum and I understand your approach of keeping YAML data clean.

As you mentioned in your post and others did in the Obsidian forum, _"this seems easily resolved by wrapping all YAML backlink values in quotes"_. The same user writes also: _"It seems that a very simple solution would be a setting to let the user choose if Obsidian recognizes backlinks within YAML"_.

I think this seems an elegant solution. The way I understand it is that Markdown has its own format and syntax. It can work with YAML which in turn has its format and its syntax. Foam/Obsidian use Markdown files as its atomic unit, so they are building a layer on top of Markdown (and YAML) conventions. What I think it is important to highlight here is that **they operate in different layers**. 

It makes sense to me that the approach of wrapping the `[[wikilink]]` inside quotes, resolves the interaction with YAML syntax, and allows Foam/Obsidian to make their work on recognizing where is a `[[wikilink]]` in order to process it. Adding a setting to control this behavior gives the power to the user on deciding whether include `[[wikilinks]]` inside YAML, or not.

I understand your idea of treating all YAML scalars as potential implicit links to avoid extra syntactic noise, but from the perspective of a Foam/Obsidian user, a `[[wikilink]]` is not much different from a regular link in the Web `https://...`, (which if you want to include one of the latter inside YAML, you better do it inside quotes too): both are understood as links, one pointing inside the other outside, but both have their own syntax. For example, I am using Google Chrome right now to write this, and the URL is rendered as `github.com/foambubble/foam/issues/557` although when I copy it looks like `https://github.com/foambubble/foam/issues/557`. It would be nice if Foam (I don't have experience using Obsidian to treat them here as equals) would offer the option to "prettify" the render of the links inside your notes, hiding the brackets and underlining and/or changing the color of the internal links, for example, without changing the original syntax. A similar behavior is performed by Markdown text editors like Typora (there are many more, but I can not recall more of them now) where the style syntax of Markdown is hidden when your text cursor is not placed in the same paragraph.

My point here is that if I have to personally choose between (1) treating all YAML scalars as potential implicit links and (2) the use of quotes to wrap a `[[wikilink]]` I would take the second option because it doesn't change my syntax for internal links (aka my way of understanding and relating with internal links). But this is a personal choice and maybe your proposal could be another option to implement and control via settings. 

What is clear is to me is that **people have the need to place links inside YAML**, weblinks or internal links, and **allowing users to navigate easily to them is the responsibility of Foam/Obsidian as interpreters of that content**.

**Comment by sbussard-google** [comment]
Is there a priority assigned to this issue? Is further discussion required? 
Perhaps this can be launched as an experimental feature?

**Comment by riccardoferretti** [comment]
My current workaround is to just have an "Associations: [[x]] [[y]] ..." (or "Relates to: ...") line at the top of the file to create those links.
I can see how that could not work for some people that maybe want to publish their text (IMO it's not a big deal, but I understand people have different needs).

I believe we shouldn't mess with YAML semantics, so I don't think we should use the `[[` syntax in YAML.
On thing that might be a possible workaround is to have a YAML field called something "associations", "connections", ... that is a YAML list, where each item is treated as a link, e.g.

```
---
title: My note
connections:
  - My other note
  - Another file
---

My content
```

I don't know how easy it would be to incorporate all existing functionalities for wikilinks there (e.g. renaming (which is coming soon), diagnostics, sections, ..), and I would only support such enhancement if we knew we can handle it. I fear that this request might make maintenance more complex, but this requires more investigation.

Because of all the reasons above I don't consider this to be a high priority issue for Foam.
Happy to get other perspectives of course.

**Comment by zachshirow** [comment]
One effective idea regarding this issue is to use inline fields in the document instead of in YAML. I'm using obsidian and sometimes I need to have a field to make a relation to another page. I was experimenting with putting that field in the frontmatter of the md document with the YAML syntax. However, wikilink was not working correctly. Then I had an idea to use inline fields to make this kind of relation. You can see my added field titled "related". 
![image](https://user-images.githubusercontent.com/84524752/197287461-9de9e8d1-9b8d-4892-9992-29079ec65605.png)

To check my theory and to confirm that dataview (an Obsidian plugin) was able to detect this field, I created a query with the following statement: 

```dataview
TABLE Related FROM "Daily notes"
```
which output the following: 
![image](https://user-images.githubusercontent.com/84524752/197287658-778880b0-5a60-443f-8fa7-6d98a5d51572.png)

As you can see, I was successfully able to add a related field to my md document on Obsidian without the restrictions created by the YAML syntax. 

One issue that is related to the inline fields in md files is that they are considered to be not well suited for editing and they are tedious. One simple solution for this would be to add your inline fields at the top of your documents right below the front matter. This way they will always be in one place and you will be able to edit them without much effort. Furthermore they will be joined with their other YAML fields all having a blast!

I hope you will find this rambling of mine useful, 

Have a great day.

**Comment by Dominic-DallOsto** [comment]
I was wondering whether we could revisit this issue in light of the (not so recent) changes to Obsidian that let it recognise wikilinks in yaml frontmatter that are surrounded by quotation marks (see [here](https://obsidian.md/changelog/2023-07-26-desktop-v1.4.0/)).

> ### About Properties
>
>
>Internal links can be added to frontmatter using the following syntax:
>```yaml
>---
>link: "[[Link]]"
>linklist:
>  - "[[Link]]"
>  - "[[Link2]]"
>---
>```

For me the main purpose of this would be to allow links to have an associated "type", that would give relations between notes some semantic meaning. To fully integrate this (to allow for example filtering backlinks and the graph view by link "type") would require more significant changes, and might be better as a separate issue actually.

**Comment by riccardoferretti** [comment]
Yes please, create a new issue. Maybe also expand on your use case as it's not fully clear what you mean and I would like to better understand
