### ISSUE TITLE
[Templates v2] Make `Foam: Open Daily Note` use a template

### ISSUE THREAD

**Issue by movermeyer** [foambubble/foam#565]
As described in #534, change `Foam: Open Daily Note` to no longer use the existing settings, but instead use a template found at `.foam/templates/daily-note.md` (or an implicit template if `.foam/templates/daily-note.md` does not exist).

Existing settings:

- `foam.openDailyNote.directory`
- `foam.openDailyNote.filenameFormat`
- `foam.openDailyNote.fileExtension`

**Comment by jonasdiemer** [comment]
Hi @movermeyer ,

struggling with my daily notes using a "long" date format (# Monday, June 21, 2021) rather than the preferred isolate (# 2021-06-21). Looks like "foam.openDailyNote.titleFormat" doesn't work anymore - is this a know issue due to your mentioned refactoring? Would be grateful for a tip on how to fix it...

Thanks!

**Comment by movermeyer** [comment]
@jonasdiemer I haven't done any work in this area yet, so its not related to this ticket. 

I just customized `foam.openDailyNote.titleFormat` (`"dddd, mmmm dS, yyyy"`) and it seems to have worked fine.

Could you please [open a new issue](https://github.com/foambubble/foam/issues/new/choose) and include the steps needed to cause the issue? Thanks!

**Comment by jonasdiemer** [comment]
Thanks. Done: https://github.com/foambubble/foam/issues/687

**Comment by janaka** [comment]
Hi, just wondering about status of this. Is it in-progress? Is there an Eta?

I'm really feeling it will give me a productivity boost.
