### ISSUE TITLE
FIle Duplication on link, when parent file is in the folder

### ISSUE THREAD

**Issue by Casyfill** [foambubble/foam#619]
- Foam version: v0.13.2
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes, I think so

When the parent file is in the folder, and I create and click on a link, two files are created
- One in the same folder (what I want)
- One in the repository root (what I don't want)

This likely to be not Foam's "own" bug
Potentially related to https://github.com/foambubble/foam/issues/545

**Steps to reproduce**
1. create folder
2. create file in the folder
3. in this file, create and click on a wikilink

**Comment by sam0109** [comment]
Do you also have the markdown notes extension installed? I encountered this same issue on Mac and resolved it by deleting that extension.

It's recommended in https://foambubble.github.io/foam/recommended-extensions but I think it's become obsolete and causes issues. If removing it fixes your issue then I think the real bug is still having it as a recommended extension in the documentation!

**Comment by riccardoferretti** [comment]
You are right, that list is obsolete, will update it

**Comment by riccardoferretti** [comment]
atm creating the placeholder in the root is the expected behavior. this should be configurable though
