### ISSUE TITLE
in Code-Server, Foam is not working

### ISSUE THREAD

**Issue by readingsnail** [foambubble/foam#633]
- Foam version: 0.13.3
- Platform: I don't know, this platform is well... at that time, i using CentOS 8
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No

**Summary**
i using iPad Air 4, you know Foam is not working iOS, so trying to https://github.com/cdr/code-server, it was not showing graph, and not showing Foam command

**Steps to reproduce**
1. all installed code-server (added Let's encrypt too)
2. cloned templete (Before, i maded and well working in my Mac)
3. not working.

comment : well, idk. Foam is very good thing, i guess. so i waiting foam in RDP or Code-Server's Foam support or Github's Codespaces. of course, may last properity of foam, i accepted it.

**Comment by dannysemi** [comment]
I noticed a couple of things about running Foam in code-server:

1. code-server doesn't use Microsoft's extension marketplace because it would violate the terms of service. The foam extension on their own marketplace is very outdated. There is an option to install extensions manually though, and the one from [open-vsx.org](https://open-vsx.org) is up-to-date.
2. If you are accessing your code-server frontend over an insecure connection then it breaks a lot of features.
3. You have to refresh the page after installing an extension.

The graph works for me using the latest version (0.14.1) and a secure connection.

**Comment by riccardoferretti** [comment]
> code-server doesn't use Microsoft's extension marketplace

@dannysemi what does it use? we could add it to the publishing workflow

**Comment by dannysemi** [comment]
They are running their own right now but they are transitioning to open-vsx.

**Comment by vJourneyman** [comment]
I manually downloaded and installed 0.14.1 on code-server and have it working.

**Comment by riccardoferretti** [comment]
> they are transitioning to open-vsx

Foam is published on open-vsx, so I guess that will solve the issue

Any update in the meantime?
