### ISSUE TITLE
`SAME_AS_ACTIVE_NOTE` and new note template issue

### ISSUE THREAD

**Issue by JakubGIT** [foambubble/foam#670]
- Foam version:  0.13.7
- Markdown Notes version:  0.0.24
- Platform: Windows
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
- `"vscodeMarkdownNotes.newNoteDirectory": "SAME_AS_ACTIVE_NOTE"` doesn't work, the new notes are created in both places `WORKSPACE_ROOT` and `SAME_AS_ACTIVE_NOTE`
- `"vscodeMarkdownNotes.newNoteTemplate": "# ${noteName}"` doesn't work properly, the new note contains `# <file name>`

- with `foam.foam-vscode` 0.9.1 and `kortina.vscode-markdown-notes` 0.0.21 it works like a charm!! a few versions ago it stopped working so I don't update any more

**Steps to reproduce**
1. download, unpack and open the zipped master of foam
2. install the plugins if needed
3. create a new folder `temp`
4. create a new file `temp/temp.md`
5. in the new file type `- [[new-note]]`
6. click on the newly written link
7. there are two new files `new-note.md`, one in root, one in `temp`
8. none of them has the first line `# New Note'

**Additional information**
I don't have any custom settings, all left default

**Comment by riccardoferretti** [comment]
The reason why you see two notes being created is that one is done by markdown notes, the other by Foam.

Most of the features of Markdown Notes have been moved into Foam itself (mostly from 0.12.0), so you don't need both extensions, and in this case they might actually conflict. If you want to keep Markdown Notes and Foam together you could use < 0.12.0

**Comment by ashleemboyer** [comment]
@riccardoferretti is there a setting similar to `"vscodeMarkdownNotes.newNoteDirectory"` to tell Foam where we want the new file created?

**Comment by riccardoferretti** [comment]
this is addressed by the template metadata (see https://github.com/foambubble/foam/issues/563) and Template V2 related issues.

Although I wonder whether a simpler setting might be useful - happy to consider it if good arguments can be made for it (and how it would interact with the template settings)

cc @movermeyer and @pderaaij in case they have comments on this

**Comment by movermeyer** [comment]
@ashleemboyer

Yeah, the [`filepath` metadata](https://github.com/foambubble/foam/blob/master/docs/features/note-templates.md#metadata) should do what you want.

---

@riccardoferretti It's not global though, since it is looking in `<workspace>/.foam/templates`. Perhaps we should add a setting for the location of a global `.foam` absolute directory, so that we fall back to that if there is no `.foam` directory in the current workspace. Perhaps it doesn't even need a setting, but just always falls back to `~/.foam`. Thoughts?

**Comment by riccardoferretti** [comment]
thinking of the user level setting is a very good point.
we already look for configuration in `~/.foam` (but tbh those are not used atm), so doing the same for templates would fit the pattern.

I fear it can get clumsy to manage on the admin side though (e.g. adding a template for the user vs the workspace), but having global templates and workspace templates can be powerful too.

That being said, I think the setting "where do I create a new note when clicking on a wikilink" is so simple that one shouldn't have to mess with templates to get the basic desired feature.
So a `newNoteDirectory` setting makes sense to me. and if a 'new-note.md' template is defined, it will take take precedence over the setting (we can also point that out in the description).

Would this make life easier for the user, or actually generate confusion in your opinion?

**Comment by ashleemboyer** [comment]
@movermeyer @riccardoferretti setting the `filepath` in the `.foam/templates/new-note.md` is correctly working for me when I execute the Create New Note command, but it is not working when I click on a wikilink for a file that does not exist. When I click the wikilink, the file is still created in the root directory of my project. Is this the expected behavior?

I personally think a `newNoteDirectory` setting would be easier than creating a template file, and I also think it would be more discoverable. For me, it's easier to look through the available settings of an extension through VSCode than it is to dig through documentation.

**Comment by movermeyer** [comment]
> is not working when I click on a wikilink for a file that does not exist. When I click the wikilink, the file is still created in the root directory of my project. Is this the expected behavior?

@ashleemboyer That hasn't been implemented yet. It's actually the next ticket I'll be working on in the [Templates v2 overhaul](https://github.com/foambubble/foam/pull/534). Follow [this issue](https://github.com/foambubble/foam/issues/566) for updates.
