### ISSUE TITLE
Backlinks case-sensitive?

### ISSUE THREAD

**Issue by jsjoeio** [foambubble/foam#68]
I have a page called `test.md` with the title `# Title`

I can reference it `[[test]]` but it seems like the auto-generated list at the bottom is case-sensitive? It only shows up when it's lowercase. See gif below. Is this expected or a bug? 

![2020-07-06 16 35 25](https://user-images.githubusercontent.com/3806031/86667710-bd528680-bfa6-11ea-90b3-b468e7fff244.gif)

**Comment by jevakallio** [comment]
This is a bug (or a known limitation of the current approach) as discovered at https://github.com/foambubble/foam/issues/50#issuecomment-654500531.

Let's keep this issue open to track progress and for others who come to report/inquire about the same, but move conversation over to #50 since @digiguru has already done ground work over there 👍

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
