### ISSUE TITLE
Non-wikilink link reference definitions do not render links in Markdown Preview

### ISSUE THREAD

**Issue by RotationMatrix** [foambubble/foam#696]
- Foam version: 0.13.8
- Platform: Mac & Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No (It does not appear the repo contains a non-wikilink link reference definition.)

**Summary**

Non-wikilink link reference definitions are not rendering links in Markdown Preview. Instead of a clickable "link" it displays "[link]".

**Steps to reproduce**

1. Open a new markdown file.
2. Paste the following text.

```
[foo]: /url "title"

[foo]
```

3. Open Markdown Preview.

**Additional information**

- I am using VSCodium 1.57.1.
- Link reference definitions render as clickable links when I install 0.13.7 or disable Foam.

Thanks for looking into this!

**Comment by pderaaij** [comment]
Capturing from the chat on Discord:

This has to do with the change of the link aliases. To make it work properly in combination with link reference definitions we've decided to make the preview ignore them. That's not a problem for auto generated references, it does breaks for the intentional reference definitions. I'll need to think if we can add some other or extra manipulation. For example, remove only the ones that we recognise as alias.
