### ISSUE TITLE
Default behaviour of generating link reference definitions

### ISSUE THREAD

**Issue by pderaaij** [foambubble/foam#723]
The default setting of Foam is to generate link reference definitions without extensions. One could wonder if this is the desired behaviour, as the link reference definitions are only required for publishing. As such, I would state you need to explicitly opt-in to the generation of link reference definitions.

I'd propose to change the default behaviour to off. Additionally we should change the settings of the foam repository to have the correct behaviour which is `withExtensions`. However, the foam repo now relies on the default behaviour of the setting.

**Comment by riccardoferretti** [comment]
I agree.

I have been conservative in this regard for backwards compatibility (otherwise an update in the extension could result into losing your definitions), but otherwise I am complete agreement that for new users can be more of a nuisance than helpful.

Note that in the `foam-template` the setting is already `off` by default: https://github.com/foambubble/foam-template/blob/e64b0d99610fe6bce66f920c15e281b1c5ade4cb/.vscode/settings.json#L16

Options:
1. change the default in the extension as well, make a note in the release notes, prepare for support (😅 ) and push it out
2. change the default in the extension as well, implement a transition wizard/tutorial
3. other ideas?

Option n.1 feels ok to me (we are in alpha), n.2 feels expensive for the problem it solves (unless we create a migration pattern, but again this feels like something post V1).

Thoughts? Preferences?

**Comment by riccardoferretti** [comment]
this has been done, Foam now defaults to OFF
