### ISSUE TITLE
Autogenerated links cannot be deleted

### ISSUE THREAD

**Issue by alexandru** [foambubble/foam#77]
I have a file like this:

```
# Personal wiki

[wiki.alexn.org](https://wiki.alexn.org/)

[//begin]: # "Autogenerated link references for markdown compatibility"
[inbox]: inbox "Inbox"
[foam-tips]: foam-tips "Foam tips"
[todo]: todo "Todo"
[//end]: # "Autogenerated link references"
```

Note that the document no longer contains the "_autogenerated link references_".

I cannot delete those references in VS Code, as it keeps adding them back on save.

To workaround the problem I closed VS Code, edited the file with another editor, then reopened VS Code.

Is this a bug? Anything I'm missing? Anything I can do to force regenerating that list of references?

**Comment by jevakallio** [comment]
@alexandru yup, it's a bug in the workspace manager, this should be fixed shortly. In the meantime you can refresh VS Code (either restart or run "Reload" in command palette, and save the file again.

**Comment by sanderdatema** [comment]
Just curious if a fix is on the way?

**Comment by j-serrand** [comment]
Hey ! Always nothing done for this issue ?

**Comment by riccardoferretti** [comment]
This should have been fixed some time ago, are you still experiencing the problem?

**Comment by j-serrand** [comment]
Yes I do, from the clean install, I just cloned the repos like said on the README, installed the VScode plugins, all is working like a charm except these annoying "Autogenerated link references for markdown compatibility" messages...

**Comment by riccardoferretti** [comment]
what do you mean by

> except these annoying "Autogenerated link references for markdown compatibility" messages

is the problem that these are being generated? you can turn that off via a setting, see here: 
https://github.com/foambubble/foam/blob/master/docs/features/link-reference-definitions.md

**Comment by j-serrand** [comment]
🤦🏻 Yes ! It was just a setting... Thanks for your help by the way !

**Comment by dominikandreas** [comment]
I have the same problem and the above link doesn't seem to exist anymore. Where can I find the setting to disable this?

**Comment by SamerKharabish** [comment]
I have the same issue. Just today cloned the repo and added a markdownfile at top level and a folder where i drag the markdownfiles that are created when using the ctrl + click keycombination on a Link. Before saving the ctrl + click keycombination on a Link works fine which brings me to the correct markdownfile. After saving the Wikilink definitions at the bottom appear and when using the ctrl + click it just brings me to the wikilinks at the bottom of the markdownfile. Changing the settings to off, withExtentions or withoutExtentions doesnt change anything.

**Comment by SamerKharabish** [comment]
I have the same. Just cloned the repo and created a md file with a link to wikilink file. At first it worked fine, but now the wikilink definitions appear everytime i save the file. This results in not being able to use the ```ctr+click```. It only brings my cursor down to the wikilinks instead of the actual file. Now i have to ```ctr+click``` in the wikilink definitions to get to my files.

Changing the ```"foam.edit.linkReferenceDefinitions"``` to any value doesnt change this behaviour.

My extentions are:
-Foam
- Code Spell Checker
- Draw.io
- German - Code Spell Checker
- GitLens
- Markdown All in One
- markdownlint
- Peacock
- Prettier

**Comment by riccardoferretti** [comment]
> It only brings my cursor down to the wikilinks instead of the actual file.

Yes unfortunately this is due to an internal VS Code change, I haven't been able to work around it 

> Changing the "foam.edit.linkReferenceDefinitions" to any value doesnt change this behaviour.

I am not sure I understand. Changing this flag means that the definitions are no longer generated. So when you click on a link it should go straight to the note. Of course you must save the file (which will remove the autogenerated references) in order to see the change.
It is not the configuration that creates the change in behavior. It's the presence of the wikilink definitions that changes the behavior.

**Comment by SamerKharabish** [comment]
> I am not sure I understand. Changing this flag means that the definitions are no longer generated. So when you click on a link it should go straight to the note. Of course you must save the file (which will remove the autogenerated references) in order to see the change. It is not the configuration that creates the change in behavior. It's the presence of the wikilink definitions that changes the behavior.

My mistake! I changed the ```"foam.edit.linkReferenceDefinitions"``` in the user settings but left them on ```"withExtentions"``` in the workspace settings. Sorry for that!
