### ISSUE TITLE
Links Not Working

### ISSUE THREAD

**Issue by Downes** [foambubble/foam#8]
Numerous links in ReadMe.md result in a 404, eg. 'Create a single Foam workspace'.

This leaves me unable to get started with Foam - The link in 'Create a GitHub repository from foam-template. If you want to keep your thoughts to yourself, remember to set the repository private.' is broken, and the instruction is otherwise too unclear.

Sorry, I don't mean to be critical - this looks like a really interesting project - but I'm stymied at step 1.

**Comment by Downes** [comment]
Problem may be the use of relative links? They are broken here https://github.com/foambubble/foam but work fine from here https://foambubble.github.io/foam/

**Comment by jevakallio** [comment]
@Downes correct, the links work in VS Code and on the rendered page in GitHub pages! Apologies for the non-obvious startup experience. The links are broken on the GitHub web UI due to the way the foam-vscode link references are created without .md extension (which would break the rendered page)

This is not ideal and I have an idea of how to fix this, but it requires a fair bit of work. I'll add it to the documentation and roadmap!

**Comment by jevakallio** [comment]
Closing as duplicate of #3, tracking resolution of root cause there. @Downes if you have further issues with this feature, let's continue conversation there.

**Comment by jevakallio** [comment]
Update: Tracking at https://github.com/foambubble/foam/issues/16
