### ISSUE TITLE
Give vsc shortcut name in docs

### ISSUE THREAD

**Issue by assignUser** [foambubble/foam#824]
Hey, thanks for the extension!

I just started using foam and had some issue with the keyboard shortcuts because mine where for what ever reason  ( probably due to windows/linux) different and it was pretty hard to find which where the shortcuts used by foam.

It would be much easier if the docs would provide the vsc name for the shortcut e.g. ` workbench.action.navigateBack` in `getting-started.md` 
https://github.com/foambubble/foam-template/blob/5ac45163ed2ac885b161b6953fdc8ac8d00f6a1a/getting-started.md?plain=1#L11

Maybe in a separate file to not clutter the other docs?

**Comment by riccardoferretti** [comment]
Hi Jacob, thanks for reaching out. 
Generally speaking, the documentation tries to strike a balance between being comprehensive, helping onboarding, without going too much into certain details that are more advanced (as I would consider this to be) and can be "recovered" elsewhere.
It seems to me that the issue here is not with Foam but with (your installation/settings) of VS Code, is that right?

So, I would adding that info in the doc slightly out of scope for an extension.

**Comment by assignUser** [comment]
It might be out of scope for the extension but it is not for the template repo and the included on boarding imho, as this is about foam (or rather the template repo) assuming a user has a certain configuration (in this case shortcuts, mac centric) and documenting this assumed config instead of users being able to use the documentation regardless of the way their system is setup.

For me this caused some frustration as I could not even try out the examples in the on boarding and had to spend some time to find the right shortcuts and it actually stopped me from starting to **use** foam. If there was a line at the bottom of each note using shortcuts like: 
>"If you are not on mac or are using non-default shortcuts you can check [[keybinds]] for the id of each shortcut used/recommended with foam"

**Comment by riccardoferretti** [comment]
My understanding is that your settings were different from the vanilla VS Code, and that caused the issue, is that incorrect?
So the issue was due to your settings, not VS Code settings in Windows.
If the documentation is not representing correctly the standard VS Code key bindings, I totally agree with you that we need to adjust it.
If instead you are using non-standard key bindings (for whatever reason), I think it's fair to expect that the standard documentation regarding key bindings won't work, no?

Am I missing something?
I am not on Windows so I can't test the set up, maybe someone who is (pinging @ingalless :) ) can help.

**Comment by assignUser** [comment]
Well the shortcuts were different, as far as I can see mostly due to being on linux (I was on windows prior so some might have been synced too).  

For example  the shortcut for formatting tables on Linux is ` ctrl+shift+I` instead of  `alt+shift+f` which I only found out because I thought it likely that this was a "markdown all in one" feature. For someone less familiar with vsc and extensions this might be a [problem]( https://foambubble.github.io/foam/principles#foam-is-for-hackers-not-only-for-programmers), so I think it would make sense to have a note with a list of shortcuts with their id so people know which extension they are from and how to find them in the settings. 

If you tell me how to pr the template I would be happy to add that.

**Comment by ingalless** [comment]
Hey! 

I see what you're getting at. But VS Code documents all this for us (see [here](https://code.visualstudio.com/docs/getstarted/keybindings#:~:text=You%20can%20view%20the%20currently,%3E%20Preferences%20%3E%20Keyboard%20Shortcuts)]). Does this cover what you have in mind?

**Comment by assignUser** [comment]
No, I don't think it does at all. See my example about formatting tables. How would the (very informative) ms documentation help me find which shortcut that is so I could check in my settings what the current binding is?

I would not have guessed that it would be the "Format Document" shortcut that uses `Markdown All In One` as a formatting provider in this case, which also has a different default on linux (which I would be able to find in the ms doc though ;) ).

Additionally there are the mac-centirc shortcuts that use `cmd`, which sometimes is replaced with `ctrl` and sometimes with `win`/`super` so it is not super clear how these will translate either.

Overall I think a list with the exact shortcut IDs so they can be found in the settings (in case you want to to look them up or change them for whatever reason) would make the documentation friendlier and prevent confusion during the first few minutes of using foam. And would follow (as hinted above) foam's principles.

Also just to be clear I don't mean a list of like every shortcut ever, just the ones used in `keyboard-shortcuts-for-editing.md` so the examples can be replicated and used while working with foam without problems.

I'll work on a pr later.
