### ISSUE TITLE
Add Markdown Preview Enhanced to recommended extensions list

### ISSUE THREAD

**Issue by krankur** [foambubble/foam#85]
https://github.com/shd101wyy/markdown-preview-enhanced This extension has a lot of useful features such as Custom CSS for Preview, Katex support, etc. and looks like a good candidate for the recommended extensions list.

**Comment by krankur** [comment]
I just noticed that https://github.com/yzhang-gh/vscode-markdown provides almost the same features as Markdown Preview Enhanced except a few differences and is already in the recommended list. Feel free to close this issue if you feel that the existing extensions already cover all the [features](https://shd101wyy.github.io/markdown-preview-enhanced/#/?id=features) that MPE provides.

**Comment by jevakallio** [comment]
@krankur thanks for submitting this! I am actually trialling markdown-preview-enhanced right now because it has native [[wiki-links]] support. I'd be ok having both in the recommended extensions since they provide slightly different value, but need to figure out how to make the UX clear, since right now in my toolbar I have two identical icons...

![image](https://user-images.githubusercontent.com/1203949/87148800-f50f4600-c2a6-11ea-9eb7-693e1cc9ab11.png)

**Comment by bclinkinbeard** [comment]
MPE's preview is much better, but links don't seem to work. Did you have that issue @jevakallio?

**Comment by SanketDG** [comment]
@bclinkinbeard What's the error?

[[Links]] also seem to not work with me, but it's because MPE expands [[Compiler Study]] to `Compiler_Study.md` for me!

**Comment by bclinkinbeard** [comment]
No error, clicking just doesn't do anything.

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
