### ISSUE TITLE
Update Documentation for 'Open Daily Note' Feature

### ISSUE THREAD

**Issue by jsjoeio** [foambubble/foam#87]
Things we should document for this new feature:
- what it is
- how to change the Filename format
- how to change the File extension
- how to change the Title format of the daily note
- how to set the Daily notes directory

Questions:
- do we remove it from the [Roadmap](https://foambubble.github.io/foam/roadmap) after implementation?
- do we remove the [implementation page](https://foambubble.github.io/foam/daily-notes)?

Based on how the docs are set up, my best guess is this would fall under a [Recipe](https://foambubble.github.io/foam/recipes). Curious to hear thoughts from @jevakallio

Related: 
- #54 
- #79

**Comment by juanfrank77** [comment]
Hey guys!

Just throwing some ideas here. 

- Would it be good to have a dedicated section for the note's settings on the VS Code UI so that people could change them there instead of going to the .vscode/settings.json?
- Make the documentation as clear as possible so that a non-dev person would know where to go and what options to enable/disable according to preference.

I think that once is completed, removing it from the roadmap and also the implementation page would be a good idea (unless the intention is to let it there as a reminder of how _far_ the project has gone 😉).

Also agree that I would be better being a Recipe under the 'write' category. Maybe something like 'Configure your daily notes'

**Comment by jsjoeio** [comment]
> Would it be good to have a dedicated section for the note's settings on the VS Code UI so that people could change them there instead of going to the .vscode/settings.json?

Good idea! You can use the Settings UI with how it's implemented right now. Here's what it will look like.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/3806031/87227671-7a4f3500-c351-11ea-8667-066832f2c0ee.png">

But if we find it hard for non-devs, we can always brainstorm how to improve the UX. For v1, this seems like it should get the job done. 

> Make the documentation as clear as possible so that a non-dev person would know where to go and what options to enable/disable according to preference.

Agreed! Definitely something we want to keep in mind. 

Thanks for adding your input! 🙏🏼 Really helpful to have a second opinion.

**Comment by riccardoferretti** [comment]
@ingalless I believe this has now been sorted, can you double check and close the issue if that's the case? thanks!

**Comment by ingalless** [comment]
Looks great to me @riccardoferretti! Thanks @jsjoeio and @juanfrank77 for your input 💪🏻
