### ISSUE TITLE
Why Foam? Why now? Why tomorrow?

### ISSUE THREAD

**Issue by jevakallio** [foambubble/foam#88]
Happy Friday everyone! 

I'm about to start my Foam hack week, and I've been thinking... the value for note taking tools is in their long term viability, but we tend to gravitate towards novelty instead. I'd love to build Foam into a tool that will grow with us. That in mind, three questions:

- What note taking tools have you used before?
- Why did you migrate away from them?
- What do you hope Foam can do support your note taking habit, now and in the future?

I'd love to hear your thoughts here, or on Discord! 
https://discord.gg/rtdZKgj

**Comment by DaniAkash** [comment]
I'll share my experience so far.

The tool I have been using: **Notion**

### Things I love about it:
- Taking notes in markdown
- Sync across all devices
- Easy to collaborate with team

### Why I migrated from Notion:
- One reason -> Ability to set up links between the notes and build a zettelkasten

I'm actually still using notion for many things, but I'm using Foam for recording my notes in Physics & Trignometry. Going forward, I plan to use it as a companion to my studies.

### What Foam can do to support my note-taking habit:
- Quickly add notes from mobile
- Reading notes from mobile with working links & graph view (if possible)

**Comment by jsjoeio** [comment]
I'll share my experience so far.

The tool I have been using: **Obsidian**

### Things I love about it:
- Taking notes in markdown
- Easy to sync to Git
- Support for Vim 
- Backlinks

### Why I migrated from Obsidian:
- Foam is built on top of VS Code which means I can use the Vim keybindings extension and get full support
- it's open source, which means I can contribute

### What Foam can do to support my note-taking habit:
- mobile app (right now, I jot things down in Notion then transfer to Foam on desktop)
- better backlink support (the casing matters and the autofill for references uses the file names instead of the headings)

**Comment by krankur** [comment]
### What note taking tools have you used before?
- Evernote
- Notion
- RemNote (Trying out currently along with Foam)
### Why did you migrate away from them?
- No or partial markdown support.
- No VIM keybindings.
- Notion didn't support inline Latex expressions (It does now, though).
- Evernote formatting is buggy.
### What do you hope Foam can do to support your note taking habit, now and in the future?
- Spaced Repetition System like Anki and RemNote
- Mobile App
- Latex support

**Comment by TianyiShi2001** [comment]
### What note taking tools have you used before?

- OneNote, Evernote, Notion
- [Bookdown](https://bookdown.org)

### Why did you migrate away from them?

- OneNote, Evernote, Notion are not based on plain markdown files. This means it is difficult to convert them to LaTeX or blog posts, for example.
- Bookdown isn't particularly suitable for notetaking. It is designed for writing traditional, hierarchically structured books. 

### What do you hope Foam can do to support your note taking habit, now and in the future?

- Any additional features must be based on plain text files (not necessarily in markdown files; there can be other configuration files)
- (optionally) support multiple flavors of markdown, particularly [pandoc-flavored markdown](http://pandoc.org), and makes it configurable per project (possibly per file, via YAML frontmatter)
- (optionally) support YAML frontmatter (see issue #86 )

**Comment by juanfrank77** [comment]
### What note taking tools have you used before?

- OneNote
- Evernote

### Why did you migrate away from them?

- OneNote never felt like a good note taking app. I pretty much used it for 2 or 3 articles and never went back.
- Evernote has been the one I've been using since 2013, but I have so many things that tagging and categorizing stuff and adding other notepad texts is another job on itself. Plus, it doesn't have a cool graph to visualize topics and notes.

### What do you hope Foam can do to support your note taking habit, now and in the future?

- Keeping the markdown files but maybe adding support for other extensions. 
- Having support for liquid tags and other sorts of embeds kinda like dev.to already has.
- The mobile app would definitely be cool.

**Comment by anku255** [comment]
## What note-taking tools have you used before?
I have used Notion and Evernote. 

## Why did you migrate away from them?
Being a programmer I have always prefered the flexibility and the ability to customize (also why I prefer android). Some other reasons are - 

- Open source and the community.
- Markdown (I love writing in markdown).
- Graph and backlinks. These are really powerful.
- Integration with VS Code and all the plugin support. Ability to create my own is a plus. There are infinite possibilities here. 
- Security (I can decide where to keep my notes)

## What do you hope Foam can do to support your note-taking habit, now and in the future?
- Migrating notes from other platforms
- Encryption (this is a wild idea and it's not something I want "right now" but it would be nice to have it.)
- Mobile and web platform would be cool.

**Comment by canadaduane** [comment]
## What note taking tools have you used before?
VS Code "Notes" plugin (I'm the author)

## Why did you migrate away from them?
I'm considering FOAM because of the graph and backlinks.

## What do you hope Foam can do support your note taking habit, now and in the future?
I'd love to integrate Notes somehow and take advantage of backlinks / indexing.

**Comment by gabekelley** [comment]
**What note taking tools have you used before?**
I've used quite a lot of these before. Starting in college it was mostly **notebooks** and a **whiteboard** near my desk, but back then I had no idea of the concept of a Second Brain or Zettelkasten or any real thought-led methodology. I've come to find those tools as integral to my work as a service/systems designer, so I went looking for tools and frameworks that assisted in their implementation. First was **Evernote**, then **Notion**. More recently I moved to **Roam**, probably in the last 8 months I'd say. I had a massive amount of notes there, was a backing True Believer, etc. Really loved the concept of wiki-links, sadly something I had not seen before.

**Why did you migrate away from them?**
I still use notebooks daily, mainly only because I have strict times throughout the day that I am away from screens but want to be able to capture thoughts for entry later.

In regards to Evernote, it got bloated and felt like I was too locked into their system, at their mercy. For Notion, the performance and offline issues got in the way, my organization was fairly haphazard since Notion lets you do whatever you want in *their ecosystem*, which by it's nature has a few opinions of it's own.

Roam, I loved. A perfect system for the way that I think. Once the True Believer system opened up, I was there. It was a system I needed in my life. I had tried Obsidian but didn't really find a home in it, something about the creators hiding themselves from the community didn't feel great to me. And then...The Roam Interview Tweets™ happened. They support some stances that within my own worldview I just could not stand by, I didn't feel right giving them a +1 on their daily user metrics I'm sure they were tracking. I exported all my notes and then systematically deleted the docs as at that time they didn't have the ability to delete a graph. I used **IA Writer** for a few days to continue working in those notes - then I found Foam!

**What do you hope Foam can do support your note taking habit, now and in the future?**
More than anything I love that Foam stays out of my way and lets me write and think the way that I want to - there are very few opinions baked into the system and I love that. There are certain improvements that are already on the roadmap, or others have brought up before me, so I'm eager to see those come through. Things like Materialized Backlinks (what a cool idea!), tags that differ from wiki-links, space repetition, mobile support or some ability to email files straight to a repo to be formatted later - some concept of quick entry.

On another note, I hope Foam sets up a tip jar so I can send my thanks in in other ways. I'm not the most gifted programmer and am out of my element building tools at a scale for the time beings, so I'd love to support the team of contributors in some other way.

**Comment by orta** [comment]
### What note taking tools have you used before?

I use both [VoodooPad](http://www.voodoopad.com) and [notational velocity](https://brettterpstra.com/projects/nvalt/) today depending on context.

### Why did/will you migrate away from them?

Maybe. I stopped using custom markdown editors also once VS Code got support to a certain bar of quality, and it's been my main MD editor for a few years. In part I'd like to give a space for the docs to live on the internet instead of just in my computer. 

### What do you hope Foam can do support your note taking habit, now and in the future?

Unsure

**Comment by dan-iel-lee** [comment]
### What note taking tools have you used before?
* Notion

### Why did/will you migrate away from them?
* I like the ability to create complex relations beyond linear parent/child

That being said, I still plan on using Notion for task related stuff (for reminders).

### What do you hope Foam can do support your note taking habit, now and in the future?
* Mobile app
* Backlink auto-generation
* Better latex support (Katex, that backend that mdmath uses, has very limited supported functions/environments)

**Comment by jonathanprozzi** [comment]
Posting some elaboration from my original answer in the Discord thread

## What note-taking tools have you used before? 

I always loved/preferred taking notes in Markdown, but gravitated to Notion last year. However, I found that for writing/note-taking, I encountered a lot of friction that I now realize is because of the hierarchical / file cabinet structure in Notion. I still use Notion and see the tremendous synergy between Notion and Foam. 

I've still been using Notion for my _intake_ - using the web capture to grab resources and store in a database that I'll then reference in Foam notes. I'm still working on this process and one of my goals is to spend more time reflecting on resources that I take in and adjust my 'consuming vs. producing' ratio.

## Why did/will you migrate away from them?

I still use Notion as a 'life operating system' (to use August Bradley's term) but have shifted entirely to Foam for my writing. I experimented with Roam and liked the approach but decided I wanted to try Foam instead. I love that Foam utilizes markdown, so the flexibility/portability appeal greatly to me. I also really like the emphasis on 'just writing' - for example, I've written more since using Foam than I have in 6 months staring at my Notion 'journal' I'm now using Notion for a lot of my intake (such as capturing from the web and storing in a database for later reflection) and then using Foam to record and link my actual thoughts on what I store in Notion.

## What do you hope Foam can do to support your note-taking habit, now and in the future?

So far, I've loved everything with Foam. I think that the roadmap is great and I'm looking forward to seeing the materialized links.

I've been using a _daily reflection_ template that I copy each day, with sections for _morning notes/pages_, _evening reflection_, and a _daily themes/thoughts_.

**Comment by thomaskoppelaar** [comment]
## What note taking tools have you used before?

Too many to count, but the most recent one was **Notion**. 

## Why did you migrate away from them?

The offline mode isn't great, and I don't have full control over my files - They stay on Notions platform for the most part.

## What do you hope Foam can do support your note taking habit, now and in the future?

I'm absolutely loving Foam. I think that it can take more advantage of linking, and have different ways of linking documents (see [RFC 5](https://github.com/foambubble/rfcs/pull/5).

**Comment by lucidBrot** [comment]
The tool I have been using: **OneNote 2016**
I'm a very new Foam user but here are my two cents.  

## Things I loved about OneNote 2016
(The points I know Foam can already do are checked)
 - [x] Easy to paste screenshots from lecture slides 
- [ ] and annotate them with text (Not really feasible in plain markdown)
- [ ] Pasted images are automatically searchable for text (Not sure how the recognized text could be stored. perhaps in the image description?)
- [x] *Everything* is doable with short key sequences because pressing <kbd>Alt</kbd>, *then* pressing <kbd>R</kbd> for example opens a specific menu. I prefer sequences over complex combinations. (VScode has much of this, though less complete)
- [x] Can link to paragraphs and jump to them (doable in markdown by using `<a id="something"></a>` and linking to `#something`)
- [x] Can attach files (Doable in markdown by simply linking to it)

## Why I migrated from OneNote 2016:
* It does not work on linux in wine. Using it in qemu is painful because I haven't figured out how to do dynamic resizing.
* The webapp is slow, and requires internet, and is not feature-complete
* I want a tool that I understand the underlying concept of. Makes it easier to migrate away, should I ever need to.
* Foam works on Windows and Linux
* I can host the syncing myself and access the files offline (not possible in the new web version of onenote)
* If there is ever an update that makes things worse, the old version will still be available since it's FOSS (btw, is there a donate button somewhere?)

## What do you hope Foam can do to support your note taking in the future?
* Markdown Features on par with Typora (e.g. highlighting using `==text==`)
* Better usability in smaller windowed mode by having an inline preview editor like Typora - or maybe a way to use Typora as editor inside VSCode? (I know I am wishing for things that probably won't happen here)
* Provide a way to avoid the autocomplete word suggestions as per [my question on discord](https://discord.com/channels/729975036148056075/729975036664086560/813035292264890378)

**Comment by nevfy-y** [comment]
### What note taking tools have you used before?

I've used Evernote a long time ago, then I used Word, then I migrated to standard notepad.exe as Word was overwhelming, then I found notion and fell in love with typing in markup. After that I also became interested in personal wikis and linking of notes, Zettelzasten and evergreen notes in particular. Alongside all of these I've used, and still using a paper bullet journal to write daily notes, and I was willing to find a good system to write more permanent long notes. I've started a small paper Zettelcasten as an experiment, but it had it's own pros and cons, and I'm not sure if it's worth continuing or not. I've started using Typora as it was quite similar to typing in Notion, but locally. Then I've found Obsidian, and it was such a pleasure to try. As an alternative to that I've tried dendron for several hours. I've tried Didiwiki but it was a bit hard for me and no so aesthetically pleasing.

### Why did you migrate away from them?
Evernote was heavy for no reason, Word is just pain now(I want to learn latex to forget about it), Notion heavily depends on internet and lacks privacy, Typora is closed source and lacks some functionality, Obsidian was so far the closest to what I've wanted, but is also closed source and has no support for 32-bit system I'm having now (I'll switch soon, but it's always a nice choice to have to reuse an old machine), and dendron and didiwiki were a bit of overload with features for me. I've needed something simple, minimal and elegant.

### What do you hope Foam can do support your note taking habit, now and in the future?

I'd like to have a simple way of adding footnotes with references from a .bib file, but may be it isn't a foam problem. Despite that I'm find this tool very enjoying. I think I'm going to stick with it for quite some time.
