### ISSUE TITLE
Publishing subsets of notes

### ISSUE THREAD

**Issue by sahil48** [foambubble/foam#90]
In most cases, to get the most value out of foam, I feel it is best to associate as many notes as possible in a single workspace. However, you may not want to export all notes in a published version or publish a subset of notes depending on the audience you are trying to engage. For this reason, I would like for foam to have a way to allow for subsets of notes to be published as a foam workspace and keep adding new notes created that fall under the same category. In my most recent issue, I suggested adding support for tags in foam documents. Tags like `#private` or `#subject` could be used to create rules on what workspaces are published by foam that can then be pushed to the appropriate server.

**Comment by riccardoferretti** [comment]
Yeah I have a similar use case, I totally agree.
For now I am "solving" this by having a custom site generator, and make the adjustments there (I haven't published anything yet so I haven't battle-tested the concept), but I agree it would make sense to at least have a recipe for this use case.

**Comment by wassona** [comment]
I've been thinking about this and haven't tried anything yet, but could this be solved by git submodules? A core set of public notes could be saved to a main module, backed up to a public repo, and private notes, or a separate subset, could be placed in their own folder within the main repo, saved as a submodule, and backed up to a separate repo with whatever privacy settings are appropriate.

Again, I haven't tried it yet, but I think that, without any changes at all, it will accomplish what I want - publishing public notes while keeping a backed up copy of private notes as part of my overall foam instance on my local machine. For publishing subsets, I assume some Foam metadata will need to be saved to the subset and that there will probably need to be a flag and some logic added to foam so that that subset can play nicely when loaded as part of the whole.

**Comment by danielarmengolaltayo** [comment]
I'm not an expert and maybe I'm missing something, but I've been testing [git submodules](https://github.blog/2016-02-01-working-with-submodules/) a bit and seems to work for this use case. Should we create a recipe for it?

**Comment by riccardoferretti** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
