### ISSUE TITLE
Collapsable indented bullets

### ISSUE THREAD

**Issue by joshhopkins** [foambubble/foam#925]
It would be great to be able to collapse indented bulleted [within the preview panel] to show/hide information. This would enable a "nested blocks" view, made popular by many note-taking applications.

**Comment by riccardoferretti** [comment]
This is possible natively with VS Code no?

**Comment by joshhopkins** [comment]
Yes, but I should clarity – I'm referring to the preview panel specifically.

**Comment by yevhenorlov** [comment]
Just to provide my two cents since I've also been thinking about this feature. Note that I haven't tried this yet, so I might be missing something.

The straightforward way of implementing this would probably look something like this: 

1. Each bullet with children is a list item with a checkbox with a specific class (to separate it from a standard markdown checkbox, e.g. `<input type="checkbox" class="collapsible">`)
2. Collapsed/open state is set via `:checked` value of the checkbox
3. Visibility of children in the preview panel is set via CSS based on that value

There are multiple challenges with this approach:
Writing HTML manually to create a collapsible checkbox is not only a hassle but also makes the document noisy. This can theoretically be avoided by customizing the markdown renderer (e.g. treat `-` as an `<input type="checkbox" class="collapsible">` instead of simply as a list item).
However, so far Foam has been unopinionated on the markdown preview tool — it doesn't go beyond recommending other extensions. So customizing the markdown renderer is probably not a problem that can be solved without breaking that principle.

**Comment by riccardoferretti** [comment]
You are correct @yevhenorlov, Foam is focused on the networked aspect of your knowledge base and tries to be as un-opinionated as possible on the details of each note (and, on the other side, on the semantics of the graph, but through the API would allow other extensions to add those).
 
Any non-Foam aware extension could enhance the preview in VS Code, it doesn't need to be aware of notes and connections. 
That's why I consider this feature to be out of scope for Foam.
